// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * AuditSettings configures audit logging behavior per tenant.
 * Audit logs track security-relevant events for compliance and forensics.
 * </pre>
 *
 * Protobuf type {@code core.v1.AuditSettings}
 */
public final class AuditSettings extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.AuditSettings)
    AuditSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      AuditSettings.class.getName());
  }
  // Use AuditSettings.newBuilder() to construct.
  private AuditSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuditSettings() {
    eventTypes_ = emptyIntList();
    externalDestination_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_AuditSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_AuditSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.AuditSettings.class, com.geniustechspace.api.core.v1.AuditSettings.Builder.class);
  }

  public static final int ENABLED_FIELD_NUMBER = 1;
  private boolean enabled_ = false;
  /**
   * <pre>
   * Enable audit logging for this tenant.
   * </pre>
   *
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int RETENTION_DAYS_FIELD_NUMBER = 2;
  private int retentionDays_ = 0;
  /**
   * <pre>
   * Audit log retention period in days.
   * Logs older than this are eligible for archival/deletion.
   * </pre>
   *
   * <code>int32 retention_days = 2 [json_name = "retentionDays", (.validate.rules) = { ... }</code>
   * @return The retentionDays.
   */
  @java.lang.Override
  public int getRetentionDays() {
    return retentionDays_;
  }

  public static final int EVENT_TYPES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList eventTypes_;
  private static final com.google.protobuf.Internal.IntListAdapter.IntConverter<
      com.geniustechspace.api.core.v1.AuditEventType> eventTypes_converter_ =
          new com.google.protobuf.Internal.IntListAdapter.IntConverter<
              com.geniustechspace.api.core.v1.AuditEventType>() {
            public com.geniustechspace.api.core.v1.AuditEventType convert(int from) {
              com.geniustechspace.api.core.v1.AuditEventType result = com.geniustechspace.api.core.v1.AuditEventType.forNumber(from);
              return result == null ? com.geniustechspace.api.core.v1.AuditEventType.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the eventTypes.
   */
  @java.lang.Override
  public java.util.List<com.geniustechspace.api.core.v1.AuditEventType> getEventTypesList() {
    return new com.google.protobuf.Internal.IntListAdapter<
        com.geniustechspace.api.core.v1.AuditEventType>(eventTypes_, eventTypes_converter_);
  }
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return The count of eventTypes.
   */
  @java.lang.Override
  public int getEventTypesCount() {
    return eventTypes_.size();
  }
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the element to return.
   * @return The eventTypes at the given index.
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.AuditEventType getEventTypes(int index) {
    return eventTypes_converter_.convert(eventTypes_.getInt(index));
  }
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the enum numeric values on the wire for eventTypes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getEventTypesValueList() {
    return eventTypes_;
  }
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of eventTypes at the given index.
   */
  @java.lang.Override
  public int getEventTypesValue(int index) {
    return eventTypes_.getInt(index);
  }
  private int eventTypesMemoizedSerializedSize;

  public static final int EXTERNAL_DESTINATION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object externalDestination_ = "";
  /**
   * <pre>
   * External audit log destination (optional).
   * URL or identifier for SIEM integration.
   * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
   * </pre>
   *
   * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
   * @return The externalDestination.
   */
  @java.lang.Override
  public java.lang.String getExternalDestination() {
    java.lang.Object ref = externalDestination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalDestination_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * External audit log destination (optional).
   * URL or identifier for SIEM integration.
   * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
   * </pre>
   *
   * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
   * @return The bytes for externalDestination.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExternalDestinationBytes() {
    java.lang.Object ref = externalDestination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalDestination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCLUDE_PII_FIELD_NUMBER = 5;
  private boolean includePii_ = false;
  /**
   * <pre>
   * Include PII (Personally Identifiable Information) in audit logs.
   * Should be false unless specifically required for compliance.
   * </pre>
   *
   * <code>bool include_pii = 5 [json_name = "includePii"];</code>
   * @return The includePii.
   */
  @java.lang.Override
  public boolean getIncludePii() {
    return includePii_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (enabled_ != false) {
      output.writeBool(1, enabled_);
    }
    if (retentionDays_ != 0) {
      output.writeInt32(2, retentionDays_);
    }
    if (getEventTypesList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(eventTypesMemoizedSerializedSize);
    }
    for (int i = 0; i < eventTypes_.size(); i++) {
      output.writeEnumNoTag(eventTypes_.getInt(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalDestination_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, externalDestination_);
    }
    if (includePii_ != false) {
      output.writeBool(5, includePii_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enabled_);
    }
    if (retentionDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, retentionDays_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < eventTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(eventTypes_.getInt(i));
      }
      size += dataSize;
      if (!getEventTypesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }eventTypesMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalDestination_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, externalDestination_);
    }
    if (includePii_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, includePii_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.AuditSettings)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.AuditSettings other = (com.geniustechspace.api.core.v1.AuditSettings) obj;

    if (getEnabled()
        != other.getEnabled()) return false;
    if (getRetentionDays()
        != other.getRetentionDays()) return false;
    if (!eventTypes_.equals(other.eventTypes_)) return false;
    if (!getExternalDestination()
        .equals(other.getExternalDestination())) return false;
    if (getIncludePii()
        != other.getIncludePii()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    hash = (37 * hash) + RETENTION_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + getRetentionDays();
    if (getEventTypesCount() > 0) {
      hash = (37 * hash) + EVENT_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + eventTypes_.hashCode();
    }
    hash = (37 * hash) + EXTERNAL_DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getExternalDestination().hashCode();
    hash = (37 * hash) + INCLUDE_PII_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludePii());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.AuditSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.AuditSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.AuditSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.AuditSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AuditSettings configures audit logging behavior per tenant.
   * Audit logs track security-relevant events for compliance and forensics.
   * </pre>
   *
   * Protobuf type {@code core.v1.AuditSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.AuditSettings)
      com.geniustechspace.api.core.v1.AuditSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_AuditSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_AuditSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.AuditSettings.class, com.geniustechspace.api.core.v1.AuditSettings.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.AuditSettings.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      enabled_ = false;
      retentionDays_ = 0;
      eventTypes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      externalDestination_ = "";
      includePii_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_AuditSettings_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.AuditSettings getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.AuditSettings build() {
      com.geniustechspace.api.core.v1.AuditSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.AuditSettings buildPartial() {
      com.geniustechspace.api.core.v1.AuditSettings result = new com.geniustechspace.api.core.v1.AuditSettings(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.geniustechspace.api.core.v1.AuditSettings result) {
      if (((bitField0_ & 0x00000004) != 0)) {
        eventTypes_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.eventTypes_ = eventTypes_;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.AuditSettings result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.enabled_ = enabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.retentionDays_ = retentionDays_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.externalDestination_ = externalDestination_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.includePii_ = includePii_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.AuditSettings) {
        return mergeFrom((com.geniustechspace.api.core.v1.AuditSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.AuditSettings other) {
      if (other == com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance()) return this;
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (other.getRetentionDays() != 0) {
        setRetentionDays(other.getRetentionDays());
      }
      if (!other.eventTypes_.isEmpty()) {
        if (eventTypes_.isEmpty()) {
          eventTypes_ = other.eventTypes_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEventTypesIsMutable();
          eventTypes_.addAll(other.eventTypes_);
        }
        onChanged();
      }
      if (!other.getExternalDestination().isEmpty()) {
        externalDestination_ = other.externalDestination_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getIncludePii() != false) {
        setIncludePii(other.getIncludePii());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              enabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              retentionDays_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int tmpRaw = input.readEnum();
              ensureEventTypesIsMutable();
              eventTypes_.addInt(tmpRaw);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureEventTypesIsMutable();
                eventTypes_.addInt(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 26
            case 34: {
              externalDestination_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              includePii_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean enabled_ ;
    /**
     * <pre>
     * Enable audit logging for this tenant.
     * </pre>
     *
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <pre>
     * Enable audit logging for this tenant.
     * </pre>
     *
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {

      enabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Enable audit logging for this tenant.
     * </pre>
     *
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      enabled_ = false;
      onChanged();
      return this;
    }

    private int retentionDays_ ;
    /**
     * <pre>
     * Audit log retention period in days.
     * Logs older than this are eligible for archival/deletion.
     * </pre>
     *
     * <code>int32 retention_days = 2 [json_name = "retentionDays", (.validate.rules) = { ... }</code>
     * @return The retentionDays.
     */
    @java.lang.Override
    public int getRetentionDays() {
      return retentionDays_;
    }
    /**
     * <pre>
     * Audit log retention period in days.
     * Logs older than this are eligible for archival/deletion.
     * </pre>
     *
     * <code>int32 retention_days = 2 [json_name = "retentionDays", (.validate.rules) = { ... }</code>
     * @param value The retentionDays to set.
     * @return This builder for chaining.
     */
    public Builder setRetentionDays(int value) {

      retentionDays_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Audit log retention period in days.
     * Logs older than this are eligible for archival/deletion.
     * </pre>
     *
     * <code>int32 retention_days = 2 [json_name = "retentionDays", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRetentionDays() {
      bitField0_ = (bitField0_ & ~0x00000002);
      retentionDays_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList eventTypes_ =
      emptyIntList();
    private void ensureEventTypesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        eventTypes_ = makeMutableCopy(eventTypes_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @return A list containing the eventTypes.
     */
    public java.util.List<com.geniustechspace.api.core.v1.AuditEventType> getEventTypesList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          com.geniustechspace.api.core.v1.AuditEventType>(eventTypes_, eventTypes_converter_);
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @return The count of eventTypes.
     */
    public int getEventTypesCount() {
      return eventTypes_.size();
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param index The index of the element to return.
     * @return The eventTypes at the given index.
     */
    public com.geniustechspace.api.core.v1.AuditEventType getEventTypes(int index) {
      return eventTypes_converter_.convert(eventTypes_.getInt(index));
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param index The index to set the value at.
     * @param value The eventTypes to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypes(
        int index, com.geniustechspace.api.core.v1.AuditEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEventTypesIsMutable();
      eventTypes_.setInt(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param value The eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addEventTypes(com.geniustechspace.api.core.v1.AuditEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEventTypesIsMutable();
      eventTypes_.addInt(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param values The eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventTypes(
        java.lang.Iterable<? extends com.geniustechspace.api.core.v1.AuditEventType> values) {
      ensureEventTypesIsMutable();
      for (com.geniustechspace.api.core.v1.AuditEventType value : values) {
        eventTypes_.addInt(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTypes() {
      eventTypes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @return A list containing the enum numeric values on the wire for eventTypes.
     */
    public java.util.List<java.lang.Integer>
    getEventTypesValueList() {
      return java.util.Collections.unmodifiableList(eventTypes_);
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of eventTypes at the given index.
     */
    public int getEventTypesValue(int index) {
      return eventTypes_.getInt(index);
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for eventTypes to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypesValue(
        int index, int value) {
      ensureEventTypesIsMutable();
      eventTypes_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param value The enum numeric value on the wire for eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addEventTypesValue(int value) {
      ensureEventTypesIsMutable();
      eventTypes_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of events to audit.
     * Fine-grained control over what gets logged.
     * </pre>
     *
     * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
     * @param values The enum numeric values on the wire for eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventTypesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureEventTypesIsMutable();
      for (int value : values) {
        eventTypes_.addInt(value);
      }
      onChanged();
      return this;
    }

    private java.lang.Object externalDestination_ = "";
    /**
     * <pre>
     * External audit log destination (optional).
     * URL or identifier for SIEM integration.
     * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
     * </pre>
     *
     * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
     * @return The externalDestination.
     */
    public java.lang.String getExternalDestination() {
      java.lang.Object ref = externalDestination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalDestination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * External audit log destination (optional).
     * URL or identifier for SIEM integration.
     * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
     * </pre>
     *
     * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
     * @return The bytes for externalDestination.
     */
    public com.google.protobuf.ByteString
        getExternalDestinationBytes() {
      java.lang.Object ref = externalDestination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalDestination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * External audit log destination (optional).
     * URL or identifier for SIEM integration.
     * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
     * </pre>
     *
     * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
     * @param value The externalDestination to set.
     * @return This builder for chaining.
     */
    public Builder setExternalDestination(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      externalDestination_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External audit log destination (optional).
     * URL or identifier for SIEM integration.
     * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
     * </pre>
     *
     * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalDestination() {
      externalDestination_ = getDefaultInstance().getExternalDestination();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External audit log destination (optional).
     * URL or identifier for SIEM integration.
     * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
     * </pre>
     *
     * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
     * @param value The bytes for externalDestination to set.
     * @return This builder for chaining.
     */
    public Builder setExternalDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      externalDestination_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean includePii_ ;
    /**
     * <pre>
     * Include PII (Personally Identifiable Information) in audit logs.
     * Should be false unless specifically required for compliance.
     * </pre>
     *
     * <code>bool include_pii = 5 [json_name = "includePii"];</code>
     * @return The includePii.
     */
    @java.lang.Override
    public boolean getIncludePii() {
      return includePii_;
    }
    /**
     * <pre>
     * Include PII (Personally Identifiable Information) in audit logs.
     * Should be false unless specifically required for compliance.
     * </pre>
     *
     * <code>bool include_pii = 5 [json_name = "includePii"];</code>
     * @param value The includePii to set.
     * @return This builder for chaining.
     */
    public Builder setIncludePii(boolean value) {

      includePii_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Include PII (Personally Identifiable Information) in audit logs.
     * Should be false unless specifically required for compliance.
     * </pre>
     *
     * <code>bool include_pii = 5 [json_name = "includePii"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludePii() {
      bitField0_ = (bitField0_ & ~0x00000010);
      includePii_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.AuditSettings)
  }

  // @@protoc_insertion_point(class_scope:core.v1.AuditSettings)
  private static final com.geniustechspace.api.core.v1.AuditSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.AuditSettings();
  }

  public static com.geniustechspace.api.core.v1.AuditSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuditSettings>
      PARSER = new com.google.protobuf.AbstractParser<AuditSettings>() {
    @java.lang.Override
    public AuditSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuditSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuditSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.AuditSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

