// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * AuditEventType categorizes security-relevant events for audit logging.
 * Each type can be individually enabled/disabled per tenant.
 * </pre>
 *
 * Protobuf enum {@code core.v1.AuditEventType}
 */
public enum AuditEventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default/unspecified event type.
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  AUDIT_EVENT_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * Authentication events (login, logout, MFA, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_AUTHENTICATION = 1;</code>
   */
  AUDIT_EVENT_TYPE_AUTHENTICATION(1),
  /**
   * <pre>
   * Authorization events (permission checks, access denied, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_AUTHORIZATION = 2;</code>
   */
  AUDIT_EVENT_TYPE_AUTHORIZATION(2),
  /**
   * <pre>
   * Data access events (read operations on sensitive data).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_DATA_ACCESS = 3;</code>
   */
  AUDIT_EVENT_TYPE_DATA_ACCESS(3),
  /**
   * <pre>
   * Data modification events (create, update, delete).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_DATA_MODIFICATION = 4;</code>
   */
  AUDIT_EVENT_TYPE_DATA_MODIFICATION(4),
  /**
   * <pre>
   * Configuration changes (tenant settings, user roles, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_CONFIGURATION_CHANGE = 5;</code>
   */
  AUDIT_EVENT_TYPE_CONFIGURATION_CHANGE(5),
  /**
   * <pre>
   * Security events (password changes, key rotation, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_SECURITY_EVENT = 6;</code>
   */
  AUDIT_EVENT_TYPE_SECURITY_EVENT(6),
  /**
   * <pre>
   * Compliance events (data export, deletion requests, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_COMPLIANCE_EVENT = 7;</code>
   */
  AUDIT_EVENT_TYPE_COMPLIANCE_EVENT(7),
  /**
   * <pre>
   * Administrative actions (user management, tenant configuration).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_ADMINISTRATIVE = 8;</code>
   */
  AUDIT_EVENT_TYPE_ADMINISTRATIVE(8),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      AuditEventType.class.getName());
  }
  /**
   * <pre>
   * Default/unspecified event type.
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int AUDIT_EVENT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Authentication events (login, logout, MFA, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_AUTHENTICATION = 1;</code>
   */
  public static final int AUDIT_EVENT_TYPE_AUTHENTICATION_VALUE = 1;
  /**
   * <pre>
   * Authorization events (permission checks, access denied, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_AUTHORIZATION = 2;</code>
   */
  public static final int AUDIT_EVENT_TYPE_AUTHORIZATION_VALUE = 2;
  /**
   * <pre>
   * Data access events (read operations on sensitive data).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_DATA_ACCESS = 3;</code>
   */
  public static final int AUDIT_EVENT_TYPE_DATA_ACCESS_VALUE = 3;
  /**
   * <pre>
   * Data modification events (create, update, delete).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_DATA_MODIFICATION = 4;</code>
   */
  public static final int AUDIT_EVENT_TYPE_DATA_MODIFICATION_VALUE = 4;
  /**
   * <pre>
   * Configuration changes (tenant settings, user roles, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_CONFIGURATION_CHANGE = 5;</code>
   */
  public static final int AUDIT_EVENT_TYPE_CONFIGURATION_CHANGE_VALUE = 5;
  /**
   * <pre>
   * Security events (password changes, key rotation, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_SECURITY_EVENT = 6;</code>
   */
  public static final int AUDIT_EVENT_TYPE_SECURITY_EVENT_VALUE = 6;
  /**
   * <pre>
   * Compliance events (data export, deletion requests, etc.).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_COMPLIANCE_EVENT = 7;</code>
   */
  public static final int AUDIT_EVENT_TYPE_COMPLIANCE_EVENT_VALUE = 7;
  /**
   * <pre>
   * Administrative actions (user management, tenant configuration).
   * </pre>
   *
   * <code>AUDIT_EVENT_TYPE_ADMINISTRATIVE = 8;</code>
   */
  public static final int AUDIT_EVENT_TYPE_ADMINISTRATIVE_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AuditEventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AuditEventType forNumber(int value) {
    switch (value) {
      case 0: return AUDIT_EVENT_TYPE_UNSPECIFIED;
      case 1: return AUDIT_EVENT_TYPE_AUTHENTICATION;
      case 2: return AUDIT_EVENT_TYPE_AUTHORIZATION;
      case 3: return AUDIT_EVENT_TYPE_DATA_ACCESS;
      case 4: return AUDIT_EVENT_TYPE_DATA_MODIFICATION;
      case 5: return AUDIT_EVENT_TYPE_CONFIGURATION_CHANGE;
      case 6: return AUDIT_EVENT_TYPE_SECURITY_EVENT;
      case 7: return AUDIT_EVENT_TYPE_COMPLIANCE_EVENT;
      case 8: return AUDIT_EVENT_TYPE_ADMINISTRATIVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AuditEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AuditEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AuditEventType>() {
          public AuditEventType findValueByNumber(int number) {
            return AuditEventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final AuditEventType[] VALUES = values();

  public static AuditEventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AuditEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:core.v1.AuditEventType)
}

