// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface AuditSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.AuditSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Enable audit logging for this tenant.
   * </pre>
   *
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <pre>
   * Audit log retention period in days.
   * Logs older than this are eligible for archival/deletion.
   * </pre>
   *
   * <code>int32 retention_days = 2 [json_name = "retentionDays", (.validate.rules) = { ... }</code>
   * @return The retentionDays.
   */
  int getRetentionDays();

  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the eventTypes.
   */
  java.util.List<com.geniustechspace.api.core.v1.AuditEventType> getEventTypesList();
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return The count of eventTypes.
   */
  int getEventTypesCount();
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the element to return.
   * @return The eventTypes at the given index.
   */
  com.geniustechspace.api.core.v1.AuditEventType getEventTypes(int index);
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the enum numeric values on the wire for eventTypes.
   */
  java.util.List<java.lang.Integer>
  getEventTypesValueList();
  /**
   * <pre>
   * Types of events to audit.
   * Fine-grained control over what gets logged.
   * </pre>
   *
   * <code>repeated .core.v1.AuditEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of eventTypes at the given index.
   */
  int getEventTypesValue(int index);

  /**
   * <pre>
   * External audit log destination (optional).
   * URL or identifier for SIEM integration.
   * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
   * </pre>
   *
   * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
   * @return The externalDestination.
   */
  java.lang.String getExternalDestination();
  /**
   * <pre>
   * External audit log destination (optional).
   * URL or identifier for SIEM integration.
   * Example: "splunk://logs.example.com" or "s3://audit-bucket/tenant-123"
   * </pre>
   *
   * <code>string external_destination = 4 [json_name = "externalDestination", (.validate.rules) = { ... }</code>
   * @return The bytes for externalDestination.
   */
  com.google.protobuf.ByteString
      getExternalDestinationBytes();

  /**
   * <pre>
   * Include PII (Personally Identifiable Information) in audit logs.
   * Should be false unless specifically required for compliance.
   * </pre>
   *
   * <code>bool include_pii = 5 [json_name = "includePii"];</code>
   * @return The includePii.
   */
  boolean getIncludePii();
}
