// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * ComplianceSettings defines regulatory and compliance requirements per tenant.
 * Different tenants may have different compliance requirements based on:
 * - Industry (healthcare, finance, etc.)
 * - Geography (GDPR in EU, etc.)
 * - Customer contracts
 * </pre>
 *
 * Protobuf type {@code core.v1.ComplianceSettings}
 */
public final class ComplianceSettings extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.ComplianceSettings)
    ComplianceSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ComplianceSettings.class.getName());
  }
  // Use ComplianceSettings.newBuilder() to construct.
  private ComplianceSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ComplianceSettings() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ComplianceSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ComplianceSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.ComplianceSettings.class, com.geniustechspace.api.core.v1.ComplianceSettings.Builder.class);
  }

  private int bitField0_;
  public static final int GDPR_ENABLED_FIELD_NUMBER = 1;
  private boolean gdprEnabled_ = false;
  /**
   * <pre>
   * GDPR (General Data Protection Regulation) compliance enabled.
   * Required for tenants with users in the European Union.
   * </pre>
   *
   * <code>bool gdpr_enabled = 1 [json_name = "gdprEnabled"];</code>
   * @return The gdprEnabled.
   */
  @java.lang.Override
  public boolean getGdprEnabled() {
    return gdprEnabled_;
  }

  public static final int HIPAA_ENABLED_FIELD_NUMBER = 2;
  private boolean hipaaEnabled_ = false;
  /**
   * <pre>
   * HIPAA (Health Insurance Portability and Accountability Act) compliance enabled.
   * Required for healthcare-related tenants in the United States.
   * </pre>
   *
   * <code>bool hipaa_enabled = 2 [json_name = "hipaaEnabled"];</code>
   * @return The hipaaEnabled.
   */
  @java.lang.Override
  public boolean getHipaaEnabled() {
    return hipaaEnabled_;
  }

  public static final int SOC2_ENABLED_FIELD_NUMBER = 3;
  private boolean soc2Enabled_ = false;
  /**
   * <pre>
   * SOC 2 compliance enabled.
   * Required for enterprise customers with security audit requirements.
   * </pre>
   *
   * <code>bool soc2_enabled = 3 [json_name = "soc2Enabled"];</code>
   * @return The soc2Enabled.
   */
  @java.lang.Override
  public boolean getSoc2Enabled() {
    return soc2Enabled_;
  }

  public static final int PCI_DSS_ENABLED_FIELD_NUMBER = 4;
  private boolean pciDssEnabled_ = false;
  /**
   * <pre>
   * PCI DSS compliance enabled.
   * Required for tenants handling payment card information.
   * </pre>
   *
   * <code>bool pci_dss_enabled = 4 [json_name = "pciDssEnabled"];</code>
   * @return The pciDssEnabled.
   */
  @java.lang.Override
  public boolean getPciDssEnabled() {
    return pciDssEnabled_;
  }

  public static final int DATA_RESIDENCY_FIELD_NUMBER = 5;
  private com.geniustechspace.api.core.v1.DataResidency dataResidency_;
  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   * @return Whether the dataResidency field is set.
   */
  @java.lang.Override
  public boolean hasDataResidency() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   * @return The dataResidency.
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.DataResidency getDataResidency() {
    return dataResidency_ == null ? com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance() : dataResidency_;
  }
  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.DataResidencyOrBuilder getDataResidencyOrBuilder() {
    return dataResidency_ == null ? com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance() : dataResidency_;
  }

  public static final int DATA_RETENTION_DAYS_FIELD_NUMBER = 6;
  private int dataRetentionDays_ = 0;
  /**
   * <pre>
   * Data retention policy in days.
   * After this period, data may be automatically deleted based on policy.
   * </pre>
   *
   * <code>int32 data_retention_days = 6 [json_name = "dataRetentionDays", (.validate.rules) = { ... }</code>
   * @return The dataRetentionDays.
   */
  @java.lang.Override
  public int getDataRetentionDays() {
    return dataRetentionDays_;
  }

  public static final int ENCRYPTION_AT_REST_REQUIRED_FIELD_NUMBER = 7;
  private boolean encryptionAtRestRequired_ = false;
  /**
   * <pre>
   * Require encryption at rest for all tenant data.
   * </pre>
   *
   * <code>bool encryption_at_rest_required = 7 [json_name = "encryptionAtRestRequired"];</code>
   * @return The encryptionAtRestRequired.
   */
  @java.lang.Override
  public boolean getEncryptionAtRestRequired() {
    return encryptionAtRestRequired_;
  }

  public static final int ENCRYPTION_IN_TRANSIT_REQUIRED_FIELD_NUMBER = 8;
  private boolean encryptionInTransitRequired_ = false;
  /**
   * <pre>
   * Require encryption in transit (TLS) for all API calls.
   * </pre>
   *
   * <code>bool encryption_in_transit_required = 8 [json_name = "encryptionInTransitRequired"];</code>
   * @return The encryptionInTransitRequired.
   */
  @java.lang.Override
  public boolean getEncryptionInTransitRequired() {
    return encryptionInTransitRequired_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gdprEnabled_ != false) {
      output.writeBool(1, gdprEnabled_);
    }
    if (hipaaEnabled_ != false) {
      output.writeBool(2, hipaaEnabled_);
    }
    if (soc2Enabled_ != false) {
      output.writeBool(3, soc2Enabled_);
    }
    if (pciDssEnabled_ != false) {
      output.writeBool(4, pciDssEnabled_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getDataResidency());
    }
    if (dataRetentionDays_ != 0) {
      output.writeInt32(6, dataRetentionDays_);
    }
    if (encryptionAtRestRequired_ != false) {
      output.writeBool(7, encryptionAtRestRequired_);
    }
    if (encryptionInTransitRequired_ != false) {
      output.writeBool(8, encryptionInTransitRequired_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gdprEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, gdprEnabled_);
    }
    if (hipaaEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hipaaEnabled_);
    }
    if (soc2Enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, soc2Enabled_);
    }
    if (pciDssEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, pciDssEnabled_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDataResidency());
    }
    if (dataRetentionDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, dataRetentionDays_);
    }
    if (encryptionAtRestRequired_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, encryptionAtRestRequired_);
    }
    if (encryptionInTransitRequired_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, encryptionInTransitRequired_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.ComplianceSettings)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.ComplianceSettings other = (com.geniustechspace.api.core.v1.ComplianceSettings) obj;

    if (getGdprEnabled()
        != other.getGdprEnabled()) return false;
    if (getHipaaEnabled()
        != other.getHipaaEnabled()) return false;
    if (getSoc2Enabled()
        != other.getSoc2Enabled()) return false;
    if (getPciDssEnabled()
        != other.getPciDssEnabled()) return false;
    if (hasDataResidency() != other.hasDataResidency()) return false;
    if (hasDataResidency()) {
      if (!getDataResidency()
          .equals(other.getDataResidency())) return false;
    }
    if (getDataRetentionDays()
        != other.getDataRetentionDays()) return false;
    if (getEncryptionAtRestRequired()
        != other.getEncryptionAtRestRequired()) return false;
    if (getEncryptionInTransitRequired()
        != other.getEncryptionInTransitRequired()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GDPR_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGdprEnabled());
    hash = (37 * hash) + HIPAA_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHipaaEnabled());
    hash = (37 * hash) + SOC2_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSoc2Enabled());
    hash = (37 * hash) + PCI_DSS_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPciDssEnabled());
    if (hasDataResidency()) {
      hash = (37 * hash) + DATA_RESIDENCY_FIELD_NUMBER;
      hash = (53 * hash) + getDataResidency().hashCode();
    }
    hash = (37 * hash) + DATA_RETENTION_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + getDataRetentionDays();
    hash = (37 * hash) + ENCRYPTION_AT_REST_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEncryptionAtRestRequired());
    hash = (37 * hash) + ENCRYPTION_IN_TRANSIT_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEncryptionInTransitRequired());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.ComplianceSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.ComplianceSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.ComplianceSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.ComplianceSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ComplianceSettings defines regulatory and compliance requirements per tenant.
   * Different tenants may have different compliance requirements based on:
   * - Industry (healthcare, finance, etc.)
   * - Geography (GDPR in EU, etc.)
   * - Customer contracts
   * </pre>
   *
   * Protobuf type {@code core.v1.ComplianceSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.ComplianceSettings)
      com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ComplianceSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ComplianceSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.ComplianceSettings.class, com.geniustechspace.api.core.v1.ComplianceSettings.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.ComplianceSettings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDataResidencyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gdprEnabled_ = false;
      hipaaEnabled_ = false;
      soc2Enabled_ = false;
      pciDssEnabled_ = false;
      dataResidency_ = null;
      if (dataResidencyBuilder_ != null) {
        dataResidencyBuilder_.dispose();
        dataResidencyBuilder_ = null;
      }
      dataRetentionDays_ = 0;
      encryptionAtRestRequired_ = false;
      encryptionInTransitRequired_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ComplianceSettings_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ComplianceSettings getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ComplianceSettings build() {
      com.geniustechspace.api.core.v1.ComplianceSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ComplianceSettings buildPartial() {
      com.geniustechspace.api.core.v1.ComplianceSettings result = new com.geniustechspace.api.core.v1.ComplianceSettings(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.ComplianceSettings result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gdprEnabled_ = gdprEnabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hipaaEnabled_ = hipaaEnabled_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.soc2Enabled_ = soc2Enabled_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pciDssEnabled_ = pciDssEnabled_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dataResidency_ = dataResidencyBuilder_ == null
            ? dataResidency_
            : dataResidencyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dataRetentionDays_ = dataRetentionDays_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.encryptionAtRestRequired_ = encryptionAtRestRequired_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.encryptionInTransitRequired_ = encryptionInTransitRequired_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.ComplianceSettings) {
        return mergeFrom((com.geniustechspace.api.core.v1.ComplianceSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.ComplianceSettings other) {
      if (other == com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance()) return this;
      if (other.getGdprEnabled() != false) {
        setGdprEnabled(other.getGdprEnabled());
      }
      if (other.getHipaaEnabled() != false) {
        setHipaaEnabled(other.getHipaaEnabled());
      }
      if (other.getSoc2Enabled() != false) {
        setSoc2Enabled(other.getSoc2Enabled());
      }
      if (other.getPciDssEnabled() != false) {
        setPciDssEnabled(other.getPciDssEnabled());
      }
      if (other.hasDataResidency()) {
        mergeDataResidency(other.getDataResidency());
      }
      if (other.getDataRetentionDays() != 0) {
        setDataRetentionDays(other.getDataRetentionDays());
      }
      if (other.getEncryptionAtRestRequired() != false) {
        setEncryptionAtRestRequired(other.getEncryptionAtRestRequired());
      }
      if (other.getEncryptionInTransitRequired() != false) {
        setEncryptionInTransitRequired(other.getEncryptionInTransitRequired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              gdprEnabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              hipaaEnabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              soc2Enabled_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              pciDssEnabled_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getDataResidencyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              dataRetentionDays_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              encryptionAtRestRequired_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              encryptionInTransitRequired_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean gdprEnabled_ ;
    /**
     * <pre>
     * GDPR (General Data Protection Regulation) compliance enabled.
     * Required for tenants with users in the European Union.
     * </pre>
     *
     * <code>bool gdpr_enabled = 1 [json_name = "gdprEnabled"];</code>
     * @return The gdprEnabled.
     */
    @java.lang.Override
    public boolean getGdprEnabled() {
      return gdprEnabled_;
    }
    /**
     * <pre>
     * GDPR (General Data Protection Regulation) compliance enabled.
     * Required for tenants with users in the European Union.
     * </pre>
     *
     * <code>bool gdpr_enabled = 1 [json_name = "gdprEnabled"];</code>
     * @param value The gdprEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setGdprEnabled(boolean value) {

      gdprEnabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * GDPR (General Data Protection Regulation) compliance enabled.
     * Required for tenants with users in the European Union.
     * </pre>
     *
     * <code>bool gdpr_enabled = 1 [json_name = "gdprEnabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGdprEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      gdprEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean hipaaEnabled_ ;
    /**
     * <pre>
     * HIPAA (Health Insurance Portability and Accountability Act) compliance enabled.
     * Required for healthcare-related tenants in the United States.
     * </pre>
     *
     * <code>bool hipaa_enabled = 2 [json_name = "hipaaEnabled"];</code>
     * @return The hipaaEnabled.
     */
    @java.lang.Override
    public boolean getHipaaEnabled() {
      return hipaaEnabled_;
    }
    /**
     * <pre>
     * HIPAA (Health Insurance Portability and Accountability Act) compliance enabled.
     * Required for healthcare-related tenants in the United States.
     * </pre>
     *
     * <code>bool hipaa_enabled = 2 [json_name = "hipaaEnabled"];</code>
     * @param value The hipaaEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setHipaaEnabled(boolean value) {

      hipaaEnabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HIPAA (Health Insurance Portability and Accountability Act) compliance enabled.
     * Required for healthcare-related tenants in the United States.
     * </pre>
     *
     * <code>bool hipaa_enabled = 2 [json_name = "hipaaEnabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHipaaEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hipaaEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean soc2Enabled_ ;
    /**
     * <pre>
     * SOC 2 compliance enabled.
     * Required for enterprise customers with security audit requirements.
     * </pre>
     *
     * <code>bool soc2_enabled = 3 [json_name = "soc2Enabled"];</code>
     * @return The soc2Enabled.
     */
    @java.lang.Override
    public boolean getSoc2Enabled() {
      return soc2Enabled_;
    }
    /**
     * <pre>
     * SOC 2 compliance enabled.
     * Required for enterprise customers with security audit requirements.
     * </pre>
     *
     * <code>bool soc2_enabled = 3 [json_name = "soc2Enabled"];</code>
     * @param value The soc2Enabled to set.
     * @return This builder for chaining.
     */
    public Builder setSoc2Enabled(boolean value) {

      soc2Enabled_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SOC 2 compliance enabled.
     * Required for enterprise customers with security audit requirements.
     * </pre>
     *
     * <code>bool soc2_enabled = 3 [json_name = "soc2Enabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSoc2Enabled() {
      bitField0_ = (bitField0_ & ~0x00000004);
      soc2Enabled_ = false;
      onChanged();
      return this;
    }

    private boolean pciDssEnabled_ ;
    /**
     * <pre>
     * PCI DSS compliance enabled.
     * Required for tenants handling payment card information.
     * </pre>
     *
     * <code>bool pci_dss_enabled = 4 [json_name = "pciDssEnabled"];</code>
     * @return The pciDssEnabled.
     */
    @java.lang.Override
    public boolean getPciDssEnabled() {
      return pciDssEnabled_;
    }
    /**
     * <pre>
     * PCI DSS compliance enabled.
     * Required for tenants handling payment card information.
     * </pre>
     *
     * <code>bool pci_dss_enabled = 4 [json_name = "pciDssEnabled"];</code>
     * @param value The pciDssEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setPciDssEnabled(boolean value) {

      pciDssEnabled_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PCI DSS compliance enabled.
     * Required for tenants handling payment card information.
     * </pre>
     *
     * <code>bool pci_dss_enabled = 4 [json_name = "pciDssEnabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPciDssEnabled() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pciDssEnabled_ = false;
      onChanged();
      return this;
    }

    private com.geniustechspace.api.core.v1.DataResidency dataResidency_;
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.DataResidency, com.geniustechspace.api.core.v1.DataResidency.Builder, com.geniustechspace.api.core.v1.DataResidencyOrBuilder> dataResidencyBuilder_;
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     * @return Whether the dataResidency field is set.
     */
    public boolean hasDataResidency() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     * @return The dataResidency.
     */
    public com.geniustechspace.api.core.v1.DataResidency getDataResidency() {
      if (dataResidencyBuilder_ == null) {
        return dataResidency_ == null ? com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance() : dataResidency_;
      } else {
        return dataResidencyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public Builder setDataResidency(com.geniustechspace.api.core.v1.DataResidency value) {
      if (dataResidencyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataResidency_ = value;
      } else {
        dataResidencyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public Builder setDataResidency(
        com.geniustechspace.api.core.v1.DataResidency.Builder builderForValue) {
      if (dataResidencyBuilder_ == null) {
        dataResidency_ = builderForValue.build();
      } else {
        dataResidencyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public Builder mergeDataResidency(com.geniustechspace.api.core.v1.DataResidency value) {
      if (dataResidencyBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          dataResidency_ != null &&
          dataResidency_ != com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance()) {
          getDataResidencyBuilder().mergeFrom(value);
        } else {
          dataResidency_ = value;
        }
      } else {
        dataResidencyBuilder_.mergeFrom(value);
      }
      if (dataResidency_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public Builder clearDataResidency() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dataResidency_ = null;
      if (dataResidencyBuilder_ != null) {
        dataResidencyBuilder_.dispose();
        dataResidencyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public com.geniustechspace.api.core.v1.DataResidency.Builder getDataResidencyBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getDataResidencyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    public com.geniustechspace.api.core.v1.DataResidencyOrBuilder getDataResidencyOrBuilder() {
      if (dataResidencyBuilder_ != null) {
        return dataResidencyBuilder_.getMessageOrBuilder();
      } else {
        return dataResidency_ == null ?
            com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance() : dataResidency_;
      }
    }
    /**
     * <pre>
     * Data residency requirements.
     * </pre>
     *
     * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.DataResidency, com.geniustechspace.api.core.v1.DataResidency.Builder, com.geniustechspace.api.core.v1.DataResidencyOrBuilder> 
        getDataResidencyFieldBuilder() {
      if (dataResidencyBuilder_ == null) {
        dataResidencyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.geniustechspace.api.core.v1.DataResidency, com.geniustechspace.api.core.v1.DataResidency.Builder, com.geniustechspace.api.core.v1.DataResidencyOrBuilder>(
                getDataResidency(),
                getParentForChildren(),
                isClean());
        dataResidency_ = null;
      }
      return dataResidencyBuilder_;
    }

    private int dataRetentionDays_ ;
    /**
     * <pre>
     * Data retention policy in days.
     * After this period, data may be automatically deleted based on policy.
     * </pre>
     *
     * <code>int32 data_retention_days = 6 [json_name = "dataRetentionDays", (.validate.rules) = { ... }</code>
     * @return The dataRetentionDays.
     */
    @java.lang.Override
    public int getDataRetentionDays() {
      return dataRetentionDays_;
    }
    /**
     * <pre>
     * Data retention policy in days.
     * After this period, data may be automatically deleted based on policy.
     * </pre>
     *
     * <code>int32 data_retention_days = 6 [json_name = "dataRetentionDays", (.validate.rules) = { ... }</code>
     * @param value The dataRetentionDays to set.
     * @return This builder for chaining.
     */
    public Builder setDataRetentionDays(int value) {

      dataRetentionDays_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data retention policy in days.
     * After this period, data may be automatically deleted based on policy.
     * </pre>
     *
     * <code>int32 data_retention_days = 6 [json_name = "dataRetentionDays", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDataRetentionDays() {
      bitField0_ = (bitField0_ & ~0x00000020);
      dataRetentionDays_ = 0;
      onChanged();
      return this;
    }

    private boolean encryptionAtRestRequired_ ;
    /**
     * <pre>
     * Require encryption at rest for all tenant data.
     * </pre>
     *
     * <code>bool encryption_at_rest_required = 7 [json_name = "encryptionAtRestRequired"];</code>
     * @return The encryptionAtRestRequired.
     */
    @java.lang.Override
    public boolean getEncryptionAtRestRequired() {
      return encryptionAtRestRequired_;
    }
    /**
     * <pre>
     * Require encryption at rest for all tenant data.
     * </pre>
     *
     * <code>bool encryption_at_rest_required = 7 [json_name = "encryptionAtRestRequired"];</code>
     * @param value The encryptionAtRestRequired to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionAtRestRequired(boolean value) {

      encryptionAtRestRequired_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Require encryption at rest for all tenant data.
     * </pre>
     *
     * <code>bool encryption_at_rest_required = 7 [json_name = "encryptionAtRestRequired"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptionAtRestRequired() {
      bitField0_ = (bitField0_ & ~0x00000040);
      encryptionAtRestRequired_ = false;
      onChanged();
      return this;
    }

    private boolean encryptionInTransitRequired_ ;
    /**
     * <pre>
     * Require encryption in transit (TLS) for all API calls.
     * </pre>
     *
     * <code>bool encryption_in_transit_required = 8 [json_name = "encryptionInTransitRequired"];</code>
     * @return The encryptionInTransitRequired.
     */
    @java.lang.Override
    public boolean getEncryptionInTransitRequired() {
      return encryptionInTransitRequired_;
    }
    /**
     * <pre>
     * Require encryption in transit (TLS) for all API calls.
     * </pre>
     *
     * <code>bool encryption_in_transit_required = 8 [json_name = "encryptionInTransitRequired"];</code>
     * @param value The encryptionInTransitRequired to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionInTransitRequired(boolean value) {

      encryptionInTransitRequired_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Require encryption in transit (TLS) for all API calls.
     * </pre>
     *
     * <code>bool encryption_in_transit_required = 8 [json_name = "encryptionInTransitRequired"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptionInTransitRequired() {
      bitField0_ = (bitField0_ & ~0x00000080);
      encryptionInTransitRequired_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.ComplianceSettings)
  }

  // @@protoc_insertion_point(class_scope:core.v1.ComplianceSettings)
  private static final com.geniustechspace.api.core.v1.ComplianceSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.ComplianceSettings();
  }

  public static com.geniustechspace.api.core.v1.ComplianceSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ComplianceSettings>
      PARSER = new com.google.protobuf.AbstractParser<ComplianceSettings>() {
    @java.lang.Override
    public ComplianceSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ComplianceSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ComplianceSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.ComplianceSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

