// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface ComplianceSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.ComplianceSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * GDPR (General Data Protection Regulation) compliance enabled.
   * Required for tenants with users in the European Union.
   * </pre>
   *
   * <code>bool gdpr_enabled = 1 [json_name = "gdprEnabled"];</code>
   * @return The gdprEnabled.
   */
  boolean getGdprEnabled();

  /**
   * <pre>
   * HIPAA (Health Insurance Portability and Accountability Act) compliance enabled.
   * Required for healthcare-related tenants in the United States.
   * </pre>
   *
   * <code>bool hipaa_enabled = 2 [json_name = "hipaaEnabled"];</code>
   * @return The hipaaEnabled.
   */
  boolean getHipaaEnabled();

  /**
   * <pre>
   * SOC 2 compliance enabled.
   * Required for enterprise customers with security audit requirements.
   * </pre>
   *
   * <code>bool soc2_enabled = 3 [json_name = "soc2Enabled"];</code>
   * @return The soc2Enabled.
   */
  boolean getSoc2Enabled();

  /**
   * <pre>
   * PCI DSS compliance enabled.
   * Required for tenants handling payment card information.
   * </pre>
   *
   * <code>bool pci_dss_enabled = 4 [json_name = "pciDssEnabled"];</code>
   * @return The pciDssEnabled.
   */
  boolean getPciDssEnabled();

  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   * @return Whether the dataResidency field is set.
   */
  boolean hasDataResidency();
  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   * @return The dataResidency.
   */
  com.geniustechspace.api.core.v1.DataResidency getDataResidency();
  /**
   * <pre>
   * Data residency requirements.
   * </pre>
   *
   * <code>.core.v1.DataResidency data_residency = 5 [json_name = "dataResidency"];</code>
   */
  com.geniustechspace.api.core.v1.DataResidencyOrBuilder getDataResidencyOrBuilder();

  /**
   * <pre>
   * Data retention policy in days.
   * After this period, data may be automatically deleted based on policy.
   * </pre>
   *
   * <code>int32 data_retention_days = 6 [json_name = "dataRetentionDays", (.validate.rules) = { ... }</code>
   * @return The dataRetentionDays.
   */
  int getDataRetentionDays();

  /**
   * <pre>
   * Require encryption at rest for all tenant data.
   * </pre>
   *
   * <code>bool encryption_at_rest_required = 7 [json_name = "encryptionAtRestRequired"];</code>
   * @return The encryptionAtRestRequired.
   */
  boolean getEncryptionAtRestRequired();

  /**
   * <pre>
   * Require encryption in transit (TLS) for all API calls.
   * </pre>
   *
   * <code>bool encryption_in_transit_required = 8 [json_name = "encryptionInTransitRequired"];</code>
   * @return The encryptionInTransitRequired.
   */
  boolean getEncryptionInTransitRequired();
}
