// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * DataResidency defines geographic restrictions on data storage.
 * Critical for compliance with regional data protection laws.
 * </pre>
 *
 * Protobuf type {@code core.v1.DataResidency}
 */
public final class DataResidency extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.DataResidency)
    DataResidencyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DataResidency.class.getName());
  }
  // Use DataResidency.newBuilder() to construct.
  private DataResidency(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DataResidency() {
    allowedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    prohibitedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    primaryRegion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_DataResidency_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_DataResidency_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.DataResidency.class, com.geniustechspace.api.core.v1.DataResidency.Builder.class);
  }

  public static final int ALLOWED_REGIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList allowedRegions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @return A list containing the allowedRegions.
   */
  public com.google.protobuf.ProtocolStringList
      getAllowedRegionsList() {
    return allowedRegions_;
  }
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @return The count of allowedRegions.
   */
  public int getAllowedRegionsCount() {
    return allowedRegions_.size();
  }
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @param index The index of the element to return.
   * @return The allowedRegions at the given index.
   */
  public java.lang.String getAllowedRegions(int index) {
    return allowedRegions_.get(index);
  }
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedRegions at the given index.
   */
  public com.google.protobuf.ByteString
      getAllowedRegionsBytes(int index) {
    return allowedRegions_.getByteString(index);
  }

  public static final int PROHIBITED_REGIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList prohibitedRegions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @return A list containing the prohibitedRegions.
   */
  public com.google.protobuf.ProtocolStringList
      getProhibitedRegionsList() {
    return prohibitedRegions_;
  }
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @return The count of prohibitedRegions.
   */
  public int getProhibitedRegionsCount() {
    return prohibitedRegions_.size();
  }
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @param index The index of the element to return.
   * @return The prohibitedRegions at the given index.
   */
  public java.lang.String getProhibitedRegions(int index) {
    return prohibitedRegions_.get(index);
  }
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the prohibitedRegions at the given index.
   */
  public com.google.protobuf.ByteString
      getProhibitedRegionsBytes(int index) {
    return prohibitedRegions_.getByteString(index);
  }

  public static final int PRIMARY_REGION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object primaryRegion_ = "";
  /**
   * <pre>
   * Primary region for data storage (preferred location).
   * Example: "US" or "EU"
   * </pre>
   *
   * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
   * @return The primaryRegion.
   */
  @java.lang.Override
  public java.lang.String getPrimaryRegion() {
    java.lang.Object ref = primaryRegion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      primaryRegion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Primary region for data storage (preferred location).
   * Example: "US" or "EU"
   * </pre>
   *
   * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
   * @return The bytes for primaryRegion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrimaryRegionBytes() {
    java.lang.Object ref = primaryRegion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      primaryRegion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < allowedRegions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, allowedRegions_.getRaw(i));
    }
    for (int i = 0; i < prohibitedRegions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, prohibitedRegions_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryRegion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, primaryRegion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < allowedRegions_.size(); i++) {
        dataSize += computeStringSizeNoTag(allowedRegions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAllowedRegionsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < prohibitedRegions_.size(); i++) {
        dataSize += computeStringSizeNoTag(prohibitedRegions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getProhibitedRegionsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryRegion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, primaryRegion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.DataResidency)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.DataResidency other = (com.geniustechspace.api.core.v1.DataResidency) obj;

    if (!getAllowedRegionsList()
        .equals(other.getAllowedRegionsList())) return false;
    if (!getProhibitedRegionsList()
        .equals(other.getProhibitedRegionsList())) return false;
    if (!getPrimaryRegion()
        .equals(other.getPrimaryRegion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAllowedRegionsCount() > 0) {
      hash = (37 * hash) + ALLOWED_REGIONS_FIELD_NUMBER;
      hash = (53 * hash) + getAllowedRegionsList().hashCode();
    }
    if (getProhibitedRegionsCount() > 0) {
      hash = (37 * hash) + PROHIBITED_REGIONS_FIELD_NUMBER;
      hash = (53 * hash) + getProhibitedRegionsList().hashCode();
    }
    hash = (37 * hash) + PRIMARY_REGION_FIELD_NUMBER;
    hash = (53 * hash) + getPrimaryRegion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.DataResidency parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.DataResidency parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.DataResidency parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.DataResidency prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DataResidency defines geographic restrictions on data storage.
   * Critical for compliance with regional data protection laws.
   * </pre>
   *
   * Protobuf type {@code core.v1.DataResidency}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.DataResidency)
      com.geniustechspace.api.core.v1.DataResidencyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_DataResidency_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_DataResidency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.DataResidency.class, com.geniustechspace.api.core.v1.DataResidency.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.DataResidency.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      allowedRegions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      prohibitedRegions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      primaryRegion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_DataResidency_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.DataResidency getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.DataResidency build() {
      com.geniustechspace.api.core.v1.DataResidency result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.DataResidency buildPartial() {
      com.geniustechspace.api.core.v1.DataResidency result = new com.geniustechspace.api.core.v1.DataResidency(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.DataResidency result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        allowedRegions_.makeImmutable();
        result.allowedRegions_ = allowedRegions_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        prohibitedRegions_.makeImmutable();
        result.prohibitedRegions_ = prohibitedRegions_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.primaryRegion_ = primaryRegion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.DataResidency) {
        return mergeFrom((com.geniustechspace.api.core.v1.DataResidency)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.DataResidency other) {
      if (other == com.geniustechspace.api.core.v1.DataResidency.getDefaultInstance()) return this;
      if (!other.allowedRegions_.isEmpty()) {
        if (allowedRegions_.isEmpty()) {
          allowedRegions_ = other.allowedRegions_;
          bitField0_ |= 0x00000001;
        } else {
          ensureAllowedRegionsIsMutable();
          allowedRegions_.addAll(other.allowedRegions_);
        }
        onChanged();
      }
      if (!other.prohibitedRegions_.isEmpty()) {
        if (prohibitedRegions_.isEmpty()) {
          prohibitedRegions_ = other.prohibitedRegions_;
          bitField0_ |= 0x00000002;
        } else {
          ensureProhibitedRegionsIsMutable();
          prohibitedRegions_.addAll(other.prohibitedRegions_);
        }
        onChanged();
      }
      if (!other.getPrimaryRegion().isEmpty()) {
        primaryRegion_ = other.primaryRegion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAllowedRegionsIsMutable();
              allowedRegions_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureProhibitedRegionsIsMutable();
              prohibitedRegions_.add(s);
              break;
            } // case 18
            case 26: {
              primaryRegion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList allowedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAllowedRegionsIsMutable() {
      if (!allowedRegions_.isModifiable()) {
        allowedRegions_ = new com.google.protobuf.LazyStringArrayList(allowedRegions_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @return A list containing the allowedRegions.
     */
    public com.google.protobuf.ProtocolStringList
        getAllowedRegionsList() {
      allowedRegions_.makeImmutable();
      return allowedRegions_;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @return The count of allowedRegions.
     */
    public int getAllowedRegionsCount() {
      return allowedRegions_.size();
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param index The index of the element to return.
     * @return The allowedRegions at the given index.
     */
    public java.lang.String getAllowedRegions(int index) {
      return allowedRegions_.get(index);
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the allowedRegions at the given index.
     */
    public com.google.protobuf.ByteString
        getAllowedRegionsBytes(int index) {
      return allowedRegions_.getByteString(index);
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param index The index to set the value at.
     * @param value The allowedRegions to set.
     * @return This builder for chaining.
     */
    public Builder setAllowedRegions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAllowedRegionsIsMutable();
      allowedRegions_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param value The allowedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addAllowedRegions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAllowedRegionsIsMutable();
      allowedRegions_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param values The allowedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addAllAllowedRegions(
        java.lang.Iterable<java.lang.String> values) {
      ensureAllowedRegionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, allowedRegions_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowedRegions() {
      allowedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
     * Example: ["US", "CA", "GB"]
     * Empty list means no restrictions.
     * </pre>
     *
     * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
     * @param value The bytes of the allowedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addAllowedRegionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAllowedRegionsIsMutable();
      allowedRegions_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList prohibitedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureProhibitedRegionsIsMutable() {
      if (!prohibitedRegions_.isModifiable()) {
        prohibitedRegions_ = new com.google.protobuf.LazyStringArrayList(prohibitedRegions_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @return A list containing the prohibitedRegions.
     */
    public com.google.protobuf.ProtocolStringList
        getProhibitedRegionsList() {
      prohibitedRegions_.makeImmutable();
      return prohibitedRegions_;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @return The count of prohibitedRegions.
     */
    public int getProhibitedRegionsCount() {
      return prohibitedRegions_.size();
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param index The index of the element to return.
     * @return The prohibitedRegions at the given index.
     */
    public java.lang.String getProhibitedRegions(int index) {
      return prohibitedRegions_.get(index);
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the prohibitedRegions at the given index.
     */
    public com.google.protobuf.ByteString
        getProhibitedRegionsBytes(int index) {
      return prohibitedRegions_.getByteString(index);
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param index The index to set the value at.
     * @param value The prohibitedRegions to set.
     * @return This builder for chaining.
     */
    public Builder setProhibitedRegions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureProhibitedRegionsIsMutable();
      prohibitedRegions_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param value The prohibitedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addProhibitedRegions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureProhibitedRegionsIsMutable();
      prohibitedRegions_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param values The prohibitedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addAllProhibitedRegions(
        java.lang.Iterable<java.lang.String> values) {
      ensureProhibitedRegionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, prohibitedRegions_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProhibitedRegions() {
      prohibitedRegions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prohibited regions where data must not be stored.
     * Takes precedence over allowed_regions.
     * Example: ["CN", "RU"]
     * </pre>
     *
     * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
     * @param value The bytes of the prohibitedRegions to add.
     * @return This builder for chaining.
     */
    public Builder addProhibitedRegionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureProhibitedRegionsIsMutable();
      prohibitedRegions_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object primaryRegion_ = "";
    /**
     * <pre>
     * Primary region for data storage (preferred location).
     * Example: "US" or "EU"
     * </pre>
     *
     * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
     * @return The primaryRegion.
     */
    public java.lang.String getPrimaryRegion() {
      java.lang.Object ref = primaryRegion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        primaryRegion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Primary region for data storage (preferred location).
     * Example: "US" or "EU"
     * </pre>
     *
     * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
     * @return The bytes for primaryRegion.
     */
    public com.google.protobuf.ByteString
        getPrimaryRegionBytes() {
      java.lang.Object ref = primaryRegion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryRegion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Primary region for data storage (preferred location).
     * Example: "US" or "EU"
     * </pre>
     *
     * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
     * @param value The primaryRegion to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryRegion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      primaryRegion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Primary region for data storage (preferred location).
     * Example: "US" or "EU"
     * </pre>
     *
     * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimaryRegion() {
      primaryRegion_ = getDefaultInstance().getPrimaryRegion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Primary region for data storage (preferred location).
     * Example: "US" or "EU"
     * </pre>
     *
     * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
     * @param value The bytes for primaryRegion to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      primaryRegion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.DataResidency)
  }

  // @@protoc_insertion_point(class_scope:core.v1.DataResidency)
  private static final com.geniustechspace.api.core.v1.DataResidency DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.DataResidency();
  }

  public static com.geniustechspace.api.core.v1.DataResidency getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataResidency>
      PARSER = new com.google.protobuf.AbstractParser<DataResidency>() {
    @java.lang.Override
    public DataResidency parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataResidency> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataResidency> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.DataResidency getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

