// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface DataResidencyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.DataResidency)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @return A list containing the allowedRegions.
   */
  java.util.List<java.lang.String>
      getAllowedRegionsList();
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @return The count of allowedRegions.
   */
  int getAllowedRegionsCount();
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @param index The index of the element to return.
   * @return The allowedRegions at the given index.
   */
  java.lang.String getAllowedRegions(int index);
  /**
   * <pre>
   * Allowed regions for data storage (ISO 3166-1 alpha-2 country codes).
   * Example: ["US", "CA", "GB"]
   * Empty list means no restrictions.
   * </pre>
   *
   * <code>repeated string allowed_regions = 1 [json_name = "allowedRegions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowedRegions at the given index.
   */
  com.google.protobuf.ByteString
      getAllowedRegionsBytes(int index);

  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @return A list containing the prohibitedRegions.
   */
  java.util.List<java.lang.String>
      getProhibitedRegionsList();
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @return The count of prohibitedRegions.
   */
  int getProhibitedRegionsCount();
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @param index The index of the element to return.
   * @return The prohibitedRegions at the given index.
   */
  java.lang.String getProhibitedRegions(int index);
  /**
   * <pre>
   * Prohibited regions where data must not be stored.
   * Takes precedence over allowed_regions.
   * Example: ["CN", "RU"]
   * </pre>
   *
   * <code>repeated string prohibited_regions = 2 [json_name = "prohibitedRegions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the prohibitedRegions at the given index.
   */
  com.google.protobuf.ByteString
      getProhibitedRegionsBytes(int index);

  /**
   * <pre>
   * Primary region for data storage (preferred location).
   * Example: "US" or "EU"
   * </pre>
   *
   * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
   * @return The primaryRegion.
   */
  java.lang.String getPrimaryRegion();
  /**
   * <pre>
   * Primary region for data storage (preferred location).
   * Example: "US" or "EU"
   * </pre>
   *
   * <code>string primary_region = 3 [json_name = "primaryRegion", (.validate.rules) = { ... }</code>
   * @return The bytes for primaryRegion.
   */
  com.google.protobuf.ByteString
      getPrimaryRegionBytes();
}
