// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface ResourceLimitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.ResourceLimits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Maximum number of users in the tenant.
   * </pre>
   *
   * <code>int32 max_users = 1 [json_name = "maxUsers", (.validate.rules) = { ... }</code>
   * @return The maxUsers.
   */
  int getMaxUsers();

  /**
   * <pre>
   * Maximum API calls per minute (rate limiting).
   * </pre>
   *
   * <code>int32 max_api_calls_per_minute = 2 [json_name = "maxApiCallsPerMinute", (.validate.rules) = { ... }</code>
   * @return The maxApiCallsPerMinute.
   */
  int getMaxApiCallsPerMinute();

  /**
   * <pre>
   * Maximum storage in bytes.
   * </pre>
   *
   * <code>int64 max_storage_bytes = 3 [json_name = "maxStorageBytes", (.validate.rules) = { ... }</code>
   * @return The maxStorageBytes.
   */
  long getMaxStorageBytes();

  /**
   * <pre>
   * Maximum concurrent active sessions.
   * </pre>
   *
   * <code>int32 max_concurrent_sessions = 4 [json_name = "maxConcurrentSessions", (.validate.rules) = { ... }</code>
   * @return The maxConcurrentSessions.
   */
  int getMaxConcurrentSessions();

  /**
   * <pre>
   * Maximum number of organizations within the tenant.
   * </pre>
   *
   * <code>int32 max_organizations = 5 [json_name = "maxOrganizations", (.validate.rules) = { ... }</code>
   * @return The maxOrganizations.
   */
  int getMaxOrganizations();

  /**
   * <pre>
   * Maximum number of workspaces per organization.
   * </pre>
   *
   * <code>int32 max_workspaces_per_org = 6 [json_name = "maxWorkspacesPerOrg", (.validate.rules) = { ... }</code>
   * @return The maxWorkspacesPerOrg.
   */
  int getMaxWorkspacesPerOrg();

  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  int getCustomLimitsCount();
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  boolean containsCustomLimits(
      java.lang.String key);
  /**
   * Use {@link #getCustomLimitsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getCustomLimits();
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getCustomLimitsMap();
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  long getCustomLimitsOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  long getCustomLimitsOrThrow(
      java.lang.String key);
}
