// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * ResourceLimits defines hard limits on tenant resource consumption.
 * These limits are enforced at runtime to prevent abuse and ensure fair use.
 * </pre>
 *
 * Protobuf type {@code core.v1.ResourceLimits}
 */
public final class ResourceLimits extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.ResourceLimits)
    ResourceLimitsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ResourceLimits.class.getName());
  }
  // Use ResourceLimits.newBuilder() to construct.
  private ResourceLimits(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResourceLimits() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 10:
        return internalGetCustomLimits();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.ResourceLimits.class, com.geniustechspace.api.core.v1.ResourceLimits.Builder.class);
  }

  public static final int MAX_USERS_FIELD_NUMBER = 1;
  private int maxUsers_ = 0;
  /**
   * <pre>
   * Maximum number of users in the tenant.
   * </pre>
   *
   * <code>int32 max_users = 1 [json_name = "maxUsers", (.validate.rules) = { ... }</code>
   * @return The maxUsers.
   */
  @java.lang.Override
  public int getMaxUsers() {
    return maxUsers_;
  }

  public static final int MAX_API_CALLS_PER_MINUTE_FIELD_NUMBER = 2;
  private int maxApiCallsPerMinute_ = 0;
  /**
   * <pre>
   * Maximum API calls per minute (rate limiting).
   * </pre>
   *
   * <code>int32 max_api_calls_per_minute = 2 [json_name = "maxApiCallsPerMinute", (.validate.rules) = { ... }</code>
   * @return The maxApiCallsPerMinute.
   */
  @java.lang.Override
  public int getMaxApiCallsPerMinute() {
    return maxApiCallsPerMinute_;
  }

  public static final int MAX_STORAGE_BYTES_FIELD_NUMBER = 3;
  private long maxStorageBytes_ = 0L;
  /**
   * <pre>
   * Maximum storage in bytes.
   * </pre>
   *
   * <code>int64 max_storage_bytes = 3 [json_name = "maxStorageBytes", (.validate.rules) = { ... }</code>
   * @return The maxStorageBytes.
   */
  @java.lang.Override
  public long getMaxStorageBytes() {
    return maxStorageBytes_;
  }

  public static final int MAX_CONCURRENT_SESSIONS_FIELD_NUMBER = 4;
  private int maxConcurrentSessions_ = 0;
  /**
   * <pre>
   * Maximum concurrent active sessions.
   * </pre>
   *
   * <code>int32 max_concurrent_sessions = 4 [json_name = "maxConcurrentSessions", (.validate.rules) = { ... }</code>
   * @return The maxConcurrentSessions.
   */
  @java.lang.Override
  public int getMaxConcurrentSessions() {
    return maxConcurrentSessions_;
  }

  public static final int MAX_ORGANIZATIONS_FIELD_NUMBER = 5;
  private int maxOrganizations_ = 0;
  /**
   * <pre>
   * Maximum number of organizations within the tenant.
   * </pre>
   *
   * <code>int32 max_organizations = 5 [json_name = "maxOrganizations", (.validate.rules) = { ... }</code>
   * @return The maxOrganizations.
   */
  @java.lang.Override
  public int getMaxOrganizations() {
    return maxOrganizations_;
  }

  public static final int MAX_WORKSPACES_PER_ORG_FIELD_NUMBER = 6;
  private int maxWorkspacesPerOrg_ = 0;
  /**
   * <pre>
   * Maximum number of workspaces per organization.
   * </pre>
   *
   * <code>int32 max_workspaces_per_org = 6 [json_name = "maxWorkspacesPerOrg", (.validate.rules) = { ... }</code>
   * @return The maxWorkspacesPerOrg.
   */
  @java.lang.Override
  public int getMaxWorkspacesPerOrg() {
    return maxWorkspacesPerOrg_;
  }

  public static final int CUSTOM_LIMITS_FIELD_NUMBER = 10;
  private static final class CustomLimitsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_CustomLimitsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> customLimits_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetCustomLimits() {
    if (customLimits_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CustomLimitsDefaultEntryHolder.defaultEntry);
    }
    return customLimits_;
  }
  public int getCustomLimitsCount() {
    return internalGetCustomLimits().getMap().size();
  }
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  @java.lang.Override
  public boolean containsCustomLimits(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetCustomLimits().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCustomLimitsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getCustomLimits() {
    return getCustomLimitsMap();
  }
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getCustomLimitsMap() {
    return internalGetCustomLimits().getMap();
  }
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  @java.lang.Override
  public long getCustomLimitsOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCustomLimits().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Custom resource limits (extensible for future requirements).
   * Key examples: "max_projects", "max_api_keys", "max_webhooks"
   * </pre>
   *
   * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
   */
  @java.lang.Override
  public long getCustomLimitsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCustomLimits().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (maxUsers_ != 0) {
      output.writeInt32(1, maxUsers_);
    }
    if (maxApiCallsPerMinute_ != 0) {
      output.writeInt32(2, maxApiCallsPerMinute_);
    }
    if (maxStorageBytes_ != 0L) {
      output.writeInt64(3, maxStorageBytes_);
    }
    if (maxConcurrentSessions_ != 0) {
      output.writeInt32(4, maxConcurrentSessions_);
    }
    if (maxOrganizations_ != 0) {
      output.writeInt32(5, maxOrganizations_);
    }
    if (maxWorkspacesPerOrg_ != 0) {
      output.writeInt32(6, maxWorkspacesPerOrg_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetCustomLimits(),
        CustomLimitsDefaultEntryHolder.defaultEntry,
        10);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (maxUsers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, maxUsers_);
    }
    if (maxApiCallsPerMinute_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, maxApiCallsPerMinute_);
    }
    if (maxStorageBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, maxStorageBytes_);
    }
    if (maxConcurrentSessions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxConcurrentSessions_);
    }
    if (maxOrganizations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxOrganizations_);
    }
    if (maxWorkspacesPerOrg_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, maxWorkspacesPerOrg_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetCustomLimits().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      customLimits__ = CustomLimitsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, customLimits__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.ResourceLimits)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.ResourceLimits other = (com.geniustechspace.api.core.v1.ResourceLimits) obj;

    if (getMaxUsers()
        != other.getMaxUsers()) return false;
    if (getMaxApiCallsPerMinute()
        != other.getMaxApiCallsPerMinute()) return false;
    if (getMaxStorageBytes()
        != other.getMaxStorageBytes()) return false;
    if (getMaxConcurrentSessions()
        != other.getMaxConcurrentSessions()) return false;
    if (getMaxOrganizations()
        != other.getMaxOrganizations()) return false;
    if (getMaxWorkspacesPerOrg()
        != other.getMaxWorkspacesPerOrg()) return false;
    if (!internalGetCustomLimits().equals(
        other.internalGetCustomLimits())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAX_USERS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxUsers();
    hash = (37 * hash) + MAX_API_CALLS_PER_MINUTE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxApiCallsPerMinute();
    hash = (37 * hash) + MAX_STORAGE_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxStorageBytes());
    hash = (37 * hash) + MAX_CONCURRENT_SESSIONS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxConcurrentSessions();
    hash = (37 * hash) + MAX_ORGANIZATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxOrganizations();
    hash = (37 * hash) + MAX_WORKSPACES_PER_ORG_FIELD_NUMBER;
    hash = (53 * hash) + getMaxWorkspacesPerOrg();
    if (!internalGetCustomLimits().getMap().isEmpty()) {
      hash = (37 * hash) + CUSTOM_LIMITS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCustomLimits().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.ResourceLimits parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.ResourceLimits parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.ResourceLimits parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.ResourceLimits prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ResourceLimits defines hard limits on tenant resource consumption.
   * These limits are enforced at runtime to prevent abuse and ensure fair use.
   * </pre>
   *
   * Protobuf type {@code core.v1.ResourceLimits}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.ResourceLimits)
      com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 10:
          return internalGetCustomLimits();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 10:
          return internalGetMutableCustomLimits();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.ResourceLimits.class, com.geniustechspace.api.core.v1.ResourceLimits.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.ResourceLimits.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      maxUsers_ = 0;
      maxApiCallsPerMinute_ = 0;
      maxStorageBytes_ = 0L;
      maxConcurrentSessions_ = 0;
      maxOrganizations_ = 0;
      maxWorkspacesPerOrg_ = 0;
      internalGetMutableCustomLimits().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_ResourceLimits_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ResourceLimits getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ResourceLimits build() {
      com.geniustechspace.api.core.v1.ResourceLimits result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.ResourceLimits buildPartial() {
      com.geniustechspace.api.core.v1.ResourceLimits result = new com.geniustechspace.api.core.v1.ResourceLimits(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.ResourceLimits result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.maxUsers_ = maxUsers_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxApiCallsPerMinute_ = maxApiCallsPerMinute_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxStorageBytes_ = maxStorageBytes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxConcurrentSessions_ = maxConcurrentSessions_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxOrganizations_ = maxOrganizations_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.maxWorkspacesPerOrg_ = maxWorkspacesPerOrg_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.customLimits_ = internalGetCustomLimits();
        result.customLimits_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.ResourceLimits) {
        return mergeFrom((com.geniustechspace.api.core.v1.ResourceLimits)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.ResourceLimits other) {
      if (other == com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance()) return this;
      if (other.getMaxUsers() != 0) {
        setMaxUsers(other.getMaxUsers());
      }
      if (other.getMaxApiCallsPerMinute() != 0) {
        setMaxApiCallsPerMinute(other.getMaxApiCallsPerMinute());
      }
      if (other.getMaxStorageBytes() != 0L) {
        setMaxStorageBytes(other.getMaxStorageBytes());
      }
      if (other.getMaxConcurrentSessions() != 0) {
        setMaxConcurrentSessions(other.getMaxConcurrentSessions());
      }
      if (other.getMaxOrganizations() != 0) {
        setMaxOrganizations(other.getMaxOrganizations());
      }
      if (other.getMaxWorkspacesPerOrg() != 0) {
        setMaxWorkspacesPerOrg(other.getMaxWorkspacesPerOrg());
      }
      internalGetMutableCustomLimits().mergeFrom(
          other.internalGetCustomLimits());
      bitField0_ |= 0x00000040;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              maxUsers_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              maxApiCallsPerMinute_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              maxStorageBytes_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              maxConcurrentSessions_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxOrganizations_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              maxWorkspacesPerOrg_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              customLimits__ = input.readMessage(
                  CustomLimitsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCustomLimits().getMutableMap().put(
                  customLimits__.getKey(), customLimits__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int maxUsers_ ;
    /**
     * <pre>
     * Maximum number of users in the tenant.
     * </pre>
     *
     * <code>int32 max_users = 1 [json_name = "maxUsers", (.validate.rules) = { ... }</code>
     * @return The maxUsers.
     */
    @java.lang.Override
    public int getMaxUsers() {
      return maxUsers_;
    }
    /**
     * <pre>
     * Maximum number of users in the tenant.
     * </pre>
     *
     * <code>int32 max_users = 1 [json_name = "maxUsers", (.validate.rules) = { ... }</code>
     * @param value The maxUsers to set.
     * @return This builder for chaining.
     */
    public Builder setMaxUsers(int value) {

      maxUsers_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of users in the tenant.
     * </pre>
     *
     * <code>int32 max_users = 1 [json_name = "maxUsers", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxUsers() {
      bitField0_ = (bitField0_ & ~0x00000001);
      maxUsers_ = 0;
      onChanged();
      return this;
    }

    private int maxApiCallsPerMinute_ ;
    /**
     * <pre>
     * Maximum API calls per minute (rate limiting).
     * </pre>
     *
     * <code>int32 max_api_calls_per_minute = 2 [json_name = "maxApiCallsPerMinute", (.validate.rules) = { ... }</code>
     * @return The maxApiCallsPerMinute.
     */
    @java.lang.Override
    public int getMaxApiCallsPerMinute() {
      return maxApiCallsPerMinute_;
    }
    /**
     * <pre>
     * Maximum API calls per minute (rate limiting).
     * </pre>
     *
     * <code>int32 max_api_calls_per_minute = 2 [json_name = "maxApiCallsPerMinute", (.validate.rules) = { ... }</code>
     * @param value The maxApiCallsPerMinute to set.
     * @return This builder for chaining.
     */
    public Builder setMaxApiCallsPerMinute(int value) {

      maxApiCallsPerMinute_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum API calls per minute (rate limiting).
     * </pre>
     *
     * <code>int32 max_api_calls_per_minute = 2 [json_name = "maxApiCallsPerMinute", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxApiCallsPerMinute() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxApiCallsPerMinute_ = 0;
      onChanged();
      return this;
    }

    private long maxStorageBytes_ ;
    /**
     * <pre>
     * Maximum storage in bytes.
     * </pre>
     *
     * <code>int64 max_storage_bytes = 3 [json_name = "maxStorageBytes", (.validate.rules) = { ... }</code>
     * @return The maxStorageBytes.
     */
    @java.lang.Override
    public long getMaxStorageBytes() {
      return maxStorageBytes_;
    }
    /**
     * <pre>
     * Maximum storage in bytes.
     * </pre>
     *
     * <code>int64 max_storage_bytes = 3 [json_name = "maxStorageBytes", (.validate.rules) = { ... }</code>
     * @param value The maxStorageBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMaxStorageBytes(long value) {

      maxStorageBytes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum storage in bytes.
     * </pre>
     *
     * <code>int64 max_storage_bytes = 3 [json_name = "maxStorageBytes", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxStorageBytes() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxStorageBytes_ = 0L;
      onChanged();
      return this;
    }

    private int maxConcurrentSessions_ ;
    /**
     * <pre>
     * Maximum concurrent active sessions.
     * </pre>
     *
     * <code>int32 max_concurrent_sessions = 4 [json_name = "maxConcurrentSessions", (.validate.rules) = { ... }</code>
     * @return The maxConcurrentSessions.
     */
    @java.lang.Override
    public int getMaxConcurrentSessions() {
      return maxConcurrentSessions_;
    }
    /**
     * <pre>
     * Maximum concurrent active sessions.
     * </pre>
     *
     * <code>int32 max_concurrent_sessions = 4 [json_name = "maxConcurrentSessions", (.validate.rules) = { ... }</code>
     * @param value The maxConcurrentSessions to set.
     * @return This builder for chaining.
     */
    public Builder setMaxConcurrentSessions(int value) {

      maxConcurrentSessions_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum concurrent active sessions.
     * </pre>
     *
     * <code>int32 max_concurrent_sessions = 4 [json_name = "maxConcurrentSessions", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxConcurrentSessions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxConcurrentSessions_ = 0;
      onChanged();
      return this;
    }

    private int maxOrganizations_ ;
    /**
     * <pre>
     * Maximum number of organizations within the tenant.
     * </pre>
     *
     * <code>int32 max_organizations = 5 [json_name = "maxOrganizations", (.validate.rules) = { ... }</code>
     * @return The maxOrganizations.
     */
    @java.lang.Override
    public int getMaxOrganizations() {
      return maxOrganizations_;
    }
    /**
     * <pre>
     * Maximum number of organizations within the tenant.
     * </pre>
     *
     * <code>int32 max_organizations = 5 [json_name = "maxOrganizations", (.validate.rules) = { ... }</code>
     * @param value The maxOrganizations to set.
     * @return This builder for chaining.
     */
    public Builder setMaxOrganizations(int value) {

      maxOrganizations_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of organizations within the tenant.
     * </pre>
     *
     * <code>int32 max_organizations = 5 [json_name = "maxOrganizations", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxOrganizations() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxOrganizations_ = 0;
      onChanged();
      return this;
    }

    private int maxWorkspacesPerOrg_ ;
    /**
     * <pre>
     * Maximum number of workspaces per organization.
     * </pre>
     *
     * <code>int32 max_workspaces_per_org = 6 [json_name = "maxWorkspacesPerOrg", (.validate.rules) = { ... }</code>
     * @return The maxWorkspacesPerOrg.
     */
    @java.lang.Override
    public int getMaxWorkspacesPerOrg() {
      return maxWorkspacesPerOrg_;
    }
    /**
     * <pre>
     * Maximum number of workspaces per organization.
     * </pre>
     *
     * <code>int32 max_workspaces_per_org = 6 [json_name = "maxWorkspacesPerOrg", (.validate.rules) = { ... }</code>
     * @param value The maxWorkspacesPerOrg to set.
     * @return This builder for chaining.
     */
    public Builder setMaxWorkspacesPerOrg(int value) {

      maxWorkspacesPerOrg_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of workspaces per organization.
     * </pre>
     *
     * <code>int32 max_workspaces_per_org = 6 [json_name = "maxWorkspacesPerOrg", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxWorkspacesPerOrg() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxWorkspacesPerOrg_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> customLimits_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetCustomLimits() {
      if (customLimits_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomLimitsDefaultEntryHolder.defaultEntry);
      }
      return customLimits_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableCustomLimits() {
      if (customLimits_ == null) {
        customLimits_ = com.google.protobuf.MapField.newMapField(
            CustomLimitsDefaultEntryHolder.defaultEntry);
      }
      if (!customLimits_.isMutable()) {
        customLimits_ = customLimits_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return customLimits_;
    }
    public int getCustomLimitsCount() {
      return internalGetCustomLimits().getMap().size();
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    @java.lang.Override
    public boolean containsCustomLimits(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCustomLimits().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomLimitsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getCustomLimits() {
      return getCustomLimitsMap();
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getCustomLimitsMap() {
      return internalGetCustomLimits().getMap();
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    @java.lang.Override
    public long getCustomLimitsOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCustomLimits().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    @java.lang.Override
    public long getCustomLimitsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCustomLimits().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearCustomLimits() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableCustomLimits().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    public Builder removeCustomLimits(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableCustomLimits().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableCustomLimits() {
      bitField0_ |= 0x00000040;
      return internalGetMutableCustomLimits().getMutableMap();
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    public Builder putCustomLimits(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableCustomLimits().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     * Custom resource limits (extensible for future requirements).
     * Key examples: "max_projects", "max_api_keys", "max_webhooks"
     * </pre>
     *
     * <code>map&lt;string, int64&gt; custom_limits = 10 [json_name = "customLimits"];</code>
     */
    public Builder putAllCustomLimits(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableCustomLimits().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.ResourceLimits)
  }

  // @@protoc_insertion_point(class_scope:core.v1.ResourceLimits)
  private static final com.geniustechspace.api.core.v1.ResourceLimits DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.ResourceLimits();
  }

  public static com.geniustechspace.api.core.v1.ResourceLimits getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceLimits>
      PARSER = new com.google.protobuf.AbstractParser<ResourceLimits>() {
    @java.lang.Override
    public ResourceLimits parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceLimits> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceLimits> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.ResourceLimits getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

