// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * SubscriptionTier determines feature availability and resource limits.
 * Higher tiers unlock more features and higher limits.
 * </pre>
 *
 * Protobuf enum {@code core.v1.SubscriptionTier}
 */
public enum SubscriptionTier
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default/unspecified tier (should not be used).
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_UNSPECIFIED = 0;</code>
   */
  SUBSCRIPTION_TIER_UNSPECIFIED(0),
  /**
   * <pre>
   * Free tier - basic features, limited resources.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_FREE = 1;</code>
   */
  SUBSCRIPTION_TIER_FREE(1),
  /**
   * <pre>
   * Basic tier - essential features for small teams.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_BASIC = 2;</code>
   */
  SUBSCRIPTION_TIER_BASIC(2),
  /**
   * <pre>
   * Professional tier - advanced features for growing teams.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_PROFESSIONAL = 3;</code>
   */
  SUBSCRIPTION_TIER_PROFESSIONAL(3),
  /**
   * <pre>
   * Enterprise tier - full feature set with premium support.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_ENTERPRISE = 4;</code>
   */
  SUBSCRIPTION_TIER_ENTERPRISE(4),
  /**
   * <pre>
   * Custom tier - bespoke configuration for large organizations.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_CUSTOM = 5;</code>
   */
  SUBSCRIPTION_TIER_CUSTOM(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SubscriptionTier.class.getName());
  }
  /**
   * <pre>
   * Default/unspecified tier (should not be used).
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_UNSPECIFIED = 0;</code>
   */
  public static final int SUBSCRIPTION_TIER_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Free tier - basic features, limited resources.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_FREE = 1;</code>
   */
  public static final int SUBSCRIPTION_TIER_FREE_VALUE = 1;
  /**
   * <pre>
   * Basic tier - essential features for small teams.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_BASIC = 2;</code>
   */
  public static final int SUBSCRIPTION_TIER_BASIC_VALUE = 2;
  /**
   * <pre>
   * Professional tier - advanced features for growing teams.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_PROFESSIONAL = 3;</code>
   */
  public static final int SUBSCRIPTION_TIER_PROFESSIONAL_VALUE = 3;
  /**
   * <pre>
   * Enterprise tier - full feature set with premium support.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_ENTERPRISE = 4;</code>
   */
  public static final int SUBSCRIPTION_TIER_ENTERPRISE_VALUE = 4;
  /**
   * <pre>
   * Custom tier - bespoke configuration for large organizations.
   * </pre>
   *
   * <code>SUBSCRIPTION_TIER_CUSTOM = 5;</code>
   */
  public static final int SUBSCRIPTION_TIER_CUSTOM_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SubscriptionTier valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SubscriptionTier forNumber(int value) {
    switch (value) {
      case 0: return SUBSCRIPTION_TIER_UNSPECIFIED;
      case 1: return SUBSCRIPTION_TIER_FREE;
      case 2: return SUBSCRIPTION_TIER_BASIC;
      case 3: return SUBSCRIPTION_TIER_PROFESSIONAL;
      case 4: return SUBSCRIPTION_TIER_ENTERPRISE;
      case 5: return SUBSCRIPTION_TIER_CUSTOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SubscriptionTier>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SubscriptionTier> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SubscriptionTier>() {
          public SubscriptionTier findValueByNumber(int number) {
            return SubscriptionTier.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final SubscriptionTier[] VALUES = values();

  public static SubscriptionTier valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SubscriptionTier(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:core.v1.SubscriptionTier)
}

