// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * TenantContext provides the isolation context for every request in the system.
 * This MUST be included in all service requests via gRPC metadata or HTTP headers.
 *
 * Usage:
 * - gRPC: Set in metadata with keys: x-tenant-id, x-organization-id, x-workspace-id
 * - HTTP: Set in headers with same keys
 * - All services MUST validate tenant context before processing requests
 * - Services MUST enforce data isolation based on this context
 * </pre>
 *
 * Protobuf type {@code core.v1.TenantContext}
 */
public final class TenantContext extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.TenantContext)
    TenantContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      TenantContext.class.getName());
  }
  // Use TenantContext.newBuilder() to construct.
  private TenantContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TenantContext() {
    tenantId_ = "";
    organizationId_ = "";
    workspaceId_ = "";
    environment_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 5:
        return internalGetMetadata();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.TenantContext.class, com.geniustechspace.api.core.v1.TenantContext.Builder.class);
  }

  public static final int TENANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Tenant identifier (REQUIRED for all requests).
   * Format: UUID v4 recommended, or custom tenant ID format.
   * Example: "550e8400-e29b-41d4-a716-446655440000"
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tenant identifier (REQUIRED for all requests).
   * Format: UUID v4 recommended, or custom tenant ID format.
   * Example: "550e8400-e29b-41d4-a716-446655440000"
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORGANIZATION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object organizationId_ = "";
  /**
   * <pre>
   * Organization identifier within the tenant (OPTIONAL).
   * Provides sub-tenant isolation for large enterprises.
   * Example: "eng-dept" or "sales-team"
   * </pre>
   *
   * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
   * @return The organizationId.
   */
  @java.lang.Override
  public java.lang.String getOrganizationId() {
    java.lang.Object ref = organizationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      organizationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Organization identifier within the tenant (OPTIONAL).
   * Provides sub-tenant isolation for large enterprises.
   * Example: "eng-dept" or "sales-team"
   * </pre>
   *
   * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
   * @return The bytes for organizationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrganizationIdBytes() {
    java.lang.Object ref = organizationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      organizationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKSPACE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object workspaceId_ = "";
  /**
   * <pre>
   * Workspace identifier within the organization (OPTIONAL).
   * Provides project/team-level isolation.
   * Example: "project-alpha" or "q4-planning"
   * </pre>
   *
   * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
   * @return The workspaceId.
   */
  @java.lang.Override
  public java.lang.String getWorkspaceId() {
    java.lang.Object ref = workspaceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workspaceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Workspace identifier within the organization (OPTIONAL).
   * Provides project/team-level isolation.
   * Example: "project-alpha" or "q4-planning"
   * </pre>
   *
   * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
   * @return The bytes for workspaceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkspaceIdBytes() {
    java.lang.Object ref = workspaceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workspaceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVIRONMENT_FIELD_NUMBER = 4;
  private int environment_ = 0;
  /**
   * <pre>
   * Environment designation for the request.
   * Used for routing, feature flags, and compliance rules.
   * </pre>
   *
   * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
   * @return The enum numeric value on the wire for environment.
   */
  @java.lang.Override public int getEnvironmentValue() {
    return environment_;
  }
  /**
   * <pre>
   * Environment designation for the request.
   * Used for routing, feature flags, and compliance rules.
   * </pre>
   *
   * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
   * @return The environment.
   */
  @java.lang.Override public com.geniustechspace.api.core.v1.Environment getEnvironment() {
    com.geniustechspace.api.core.v1.Environment result = com.geniustechspace.api.core.v1.Environment.forNumber(environment_);
    return result == null ? com.geniustechspace.api.core.v1.Environment.UNRECOGNIZED : result;
  }

  public static final int METADATA_FIELD_NUMBER = 5;
  private static final class MetadataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_MetadataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metadata_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetadata() {
    if (metadata_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetadataDefaultEntryHolder.defaultEntry);
    }
    return metadata_;
  }
  public int getMetadataCount() {
    return internalGetMetadata().getMap().size();
  }
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public boolean containsMetadata(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetadata().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
    return getMetadataMap();
  }
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
    return internalGetMetadata().getMap();
  }
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.lang.String getMetadataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(organizationId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, organizationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, workspaceId_);
    }
    if (environment_ != com.geniustechspace.api.core.v1.Environment.ENVIRONMENT_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, environment_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetMetadata(),
        MetadataDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(organizationId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, organizationId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(workspaceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, workspaceId_);
    }
    if (environment_ != com.geniustechspace.api.core.v1.Environment.ENVIRONMENT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, environment_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetadata().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, metadata__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.TenantContext)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.TenantContext other = (com.geniustechspace.api.core.v1.TenantContext) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getOrganizationId()
        .equals(other.getOrganizationId())) return false;
    if (!getWorkspaceId()
        .equals(other.getWorkspaceId())) return false;
    if (environment_ != other.environment_) return false;
    if (!internalGetMetadata().equals(
        other.internalGetMetadata())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + ORGANIZATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrganizationId().hashCode();
    hash = (37 * hash) + WORKSPACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkspaceId().hashCode();
    hash = (37 * hash) + ENVIRONMENT_FIELD_NUMBER;
    hash = (53 * hash) + environment_;
    if (!internalGetMetadata().getMap().isEmpty()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.TenantContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.TenantContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.TenantContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.TenantContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TenantContext provides the isolation context for every request in the system.
   * This MUST be included in all service requests via gRPC metadata or HTTP headers.
   *
   * Usage:
   * - gRPC: Set in metadata with keys: x-tenant-id, x-organization-id, x-workspace-id
   * - HTTP: Set in headers with same keys
   * - All services MUST validate tenant context before processing requests
   * - Services MUST enforce data isolation based on this context
   * </pre>
   *
   * Protobuf type {@code core.v1.TenantContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.TenantContext)
      com.geniustechspace.api.core.v1.TenantContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.TenantContext.class, com.geniustechspace.api.core.v1.TenantContext.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.TenantContext.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = "";
      organizationId_ = "";
      workspaceId_ = "";
      environment_ = 0;
      internalGetMutableMetadata().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantContext_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantContext getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.TenantContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantContext build() {
      com.geniustechspace.api.core.v1.TenantContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantContext buildPartial() {
      com.geniustechspace.api.core.v1.TenantContext result = new com.geniustechspace.api.core.v1.TenantContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.TenantContext result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.organizationId_ = organizationId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.workspaceId_ = workspaceId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.environment_ = environment_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.TenantContext) {
        return mergeFrom((com.geniustechspace.api.core.v1.TenantContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.TenantContext other) {
      if (other == com.geniustechspace.api.core.v1.TenantContext.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOrganizationId().isEmpty()) {
        organizationId_ = other.organizationId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getWorkspaceId().isEmpty()) {
        workspaceId_ = other.workspaceId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.environment_ != 0) {
        setEnvironmentValue(other.getEnvironmentValue());
      }
      internalGetMutableMetadata().mergeFrom(
          other.internalGetMetadata());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              organizationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              workspaceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              environment_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetadata().getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Tenant identifier (REQUIRED for all requests).
     * Format: UUID v4 recommended, or custom tenant ID format.
     * Example: "550e8400-e29b-41d4-a716-446655440000"
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tenant identifier (REQUIRED for all requests).
     * Format: UUID v4 recommended, or custom tenant ID format.
     * Example: "550e8400-e29b-41d4-a716-446655440000"
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tenant identifier (REQUIRED for all requests).
     * Format: UUID v4 recommended, or custom tenant ID format.
     * Example: "550e8400-e29b-41d4-a716-446655440000"
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant identifier (REQUIRED for all requests).
     * Format: UUID v4 recommended, or custom tenant ID format.
     * Example: "550e8400-e29b-41d4-a716-446655440000"
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant identifier (REQUIRED for all requests).
     * Format: UUID v4 recommended, or custom tenant ID format.
     * Example: "550e8400-e29b-41d4-a716-446655440000"
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object organizationId_ = "";
    /**
     * <pre>
     * Organization identifier within the tenant (OPTIONAL).
     * Provides sub-tenant isolation for large enterprises.
     * Example: "eng-dept" or "sales-team"
     * </pre>
     *
     * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
     * @return The organizationId.
     */
    public java.lang.String getOrganizationId() {
      java.lang.Object ref = organizationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        organizationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Organization identifier within the tenant (OPTIONAL).
     * Provides sub-tenant isolation for large enterprises.
     * Example: "eng-dept" or "sales-team"
     * </pre>
     *
     * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
     * @return The bytes for organizationId.
     */
    public com.google.protobuf.ByteString
        getOrganizationIdBytes() {
      java.lang.Object ref = organizationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        organizationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Organization identifier within the tenant (OPTIONAL).
     * Provides sub-tenant isolation for large enterprises.
     * Example: "eng-dept" or "sales-team"
     * </pre>
     *
     * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
     * @param value The organizationId to set.
     * @return This builder for chaining.
     */
    public Builder setOrganizationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      organizationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Organization identifier within the tenant (OPTIONAL).
     * Provides sub-tenant isolation for large enterprises.
     * Example: "eng-dept" or "sales-team"
     * </pre>
     *
     * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearOrganizationId() {
      organizationId_ = getDefaultInstance().getOrganizationId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Organization identifier within the tenant (OPTIONAL).
     * Provides sub-tenant isolation for large enterprises.
     * Example: "eng-dept" or "sales-team"
     * </pre>
     *
     * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
     * @param value The bytes for organizationId to set.
     * @return This builder for chaining.
     */
    public Builder setOrganizationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      organizationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object workspaceId_ = "";
    /**
     * <pre>
     * Workspace identifier within the organization (OPTIONAL).
     * Provides project/team-level isolation.
     * Example: "project-alpha" or "q4-planning"
     * </pre>
     *
     * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
     * @return The workspaceId.
     */
    public java.lang.String getWorkspaceId() {
      java.lang.Object ref = workspaceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workspaceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Workspace identifier within the organization (OPTIONAL).
     * Provides project/team-level isolation.
     * Example: "project-alpha" or "q4-planning"
     * </pre>
     *
     * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
     * @return The bytes for workspaceId.
     */
    public com.google.protobuf.ByteString
        getWorkspaceIdBytes() {
      java.lang.Object ref = workspaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workspaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Workspace identifier within the organization (OPTIONAL).
     * Provides project/team-level isolation.
     * Example: "project-alpha" or "q4-planning"
     * </pre>
     *
     * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
     * @param value The workspaceId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspaceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      workspaceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Workspace identifier within the organization (OPTIONAL).
     * Provides project/team-level isolation.
     * Example: "project-alpha" or "q4-planning"
     * </pre>
     *
     * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkspaceId() {
      workspaceId_ = getDefaultInstance().getWorkspaceId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Workspace identifier within the organization (OPTIONAL).
     * Provides project/team-level isolation.
     * Example: "project-alpha" or "q4-planning"
     * </pre>
     *
     * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
     * @param value The bytes for workspaceId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      workspaceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int environment_ = 0;
    /**
     * <pre>
     * Environment designation for the request.
     * Used for routing, feature flags, and compliance rules.
     * </pre>
     *
     * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
     * @return The enum numeric value on the wire for environment.
     */
    @java.lang.Override public int getEnvironmentValue() {
      return environment_;
    }
    /**
     * <pre>
     * Environment designation for the request.
     * Used for routing, feature flags, and compliance rules.
     * </pre>
     *
     * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
     * @param value The enum numeric value on the wire for environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentValue(int value) {
      environment_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Environment designation for the request.
     * Used for routing, feature flags, and compliance rules.
     * </pre>
     *
     * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
     * @return The environment.
     */
    @java.lang.Override
    public com.geniustechspace.api.core.v1.Environment getEnvironment() {
      com.geniustechspace.api.core.v1.Environment result = com.geniustechspace.api.core.v1.Environment.forNumber(environment_);
      return result == null ? com.geniustechspace.api.core.v1.Environment.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Environment designation for the request.
     * Used for routing, feature flags, and compliance rules.
     * </pre>
     *
     * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
     * @param value The environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironment(com.geniustechspace.api.core.v1.Environment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      environment_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Environment designation for the request.
     * Used for routing, feature flags, and compliance rules.
     * </pre>
     *
     * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironment() {
      bitField0_ = (bitField0_ & ~0x00000008);
      environment_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadata() {
      if (metadata_ == null) {
        metadata_ = com.google.protobuf.MapField.newMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.copy();
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableMetadata().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    public Builder removeMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetadata().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadata() {
      bitField0_ |= 0x00000010;
      return internalGetMutableMetadata().getMutableMap();
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    public Builder putMetadata(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetadata().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * Additional tenant-specific metadata for routing and policy decisions.
     * Can include feature flags, A/B test groups, etc.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
     */
    public Builder putAllMetadata(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetadata().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.TenantContext)
  }

  // @@protoc_insertion_point(class_scope:core.v1.TenantContext)
  private static final com.geniustechspace.api.core.v1.TenantContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.TenantContext();
  }

  public static com.geniustechspace.api.core.v1.TenantContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TenantContext>
      PARSER = new com.google.protobuf.AbstractParser<TenantContext>() {
    @java.lang.Override
    public TenantContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TenantContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TenantContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.TenantContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

