// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface TenantContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.TenantContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tenant identifier (REQUIRED for all requests).
   * Format: UUID v4 recommended, or custom tenant ID format.
   * Example: "550e8400-e29b-41d4-a716-446655440000"
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * Tenant identifier (REQUIRED for all requests).
   * Format: UUID v4 recommended, or custom tenant ID format.
   * Example: "550e8400-e29b-41d4-a716-446655440000"
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * Organization identifier within the tenant (OPTIONAL).
   * Provides sub-tenant isolation for large enterprises.
   * Example: "eng-dept" or "sales-team"
   * </pre>
   *
   * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
   * @return The organizationId.
   */
  java.lang.String getOrganizationId();
  /**
   * <pre>
   * Organization identifier within the tenant (OPTIONAL).
   * Provides sub-tenant isolation for large enterprises.
   * Example: "eng-dept" or "sales-team"
   * </pre>
   *
   * <code>string organization_id = 2 [json_name = "organizationId", (.validate.rules) = { ... }</code>
   * @return The bytes for organizationId.
   */
  com.google.protobuf.ByteString
      getOrganizationIdBytes();

  /**
   * <pre>
   * Workspace identifier within the organization (OPTIONAL).
   * Provides project/team-level isolation.
   * Example: "project-alpha" or "q4-planning"
   * </pre>
   *
   * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
   * @return The workspaceId.
   */
  java.lang.String getWorkspaceId();
  /**
   * <pre>
   * Workspace identifier within the organization (OPTIONAL).
   * Provides project/team-level isolation.
   * Example: "project-alpha" or "q4-planning"
   * </pre>
   *
   * <code>string workspace_id = 3 [json_name = "workspaceId", (.validate.rules) = { ... }</code>
   * @return The bytes for workspaceId.
   */
  com.google.protobuf.ByteString
      getWorkspaceIdBytes();

  /**
   * <pre>
   * Environment designation for the request.
   * Used for routing, feature flags, and compliance rules.
   * </pre>
   *
   * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
   * @return The enum numeric value on the wire for environment.
   */
  int getEnvironmentValue();
  /**
   * <pre>
   * Environment designation for the request.
   * Used for routing, feature flags, and compliance rules.
   * </pre>
   *
   * <code>.core.v1.Environment environment = 4 [json_name = "environment"];</code>
   * @return The environment.
   */
  com.geniustechspace.api.core.v1.Environment getEnvironment();

  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  int getMetadataCount();
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Additional tenant-specific metadata for routing and policy decisions.
   * Can include feature flags, A/B test groups, etc.
   * </pre>
   *
   * <code>map&lt;string, string&gt; metadata = 5 [json_name = "metadata"];</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);
}
