// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * TenantStatus represents the operational state of a tenant.
 * Status transitions are controlled and audited.
 * </pre>
 *
 * Protobuf enum {@code core.v1.TenantStatus}
 */
public enum TenantStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default/unspecified status (invalid).
   * </pre>
   *
   * <code>TENANT_STATUS_UNSPECIFIED = 0;</code>
   */
  TENANT_STATUS_UNSPECIFIED(0),
  /**
   * <pre>
   * Active - tenant is operational and can make requests.
   * </pre>
   *
   * <code>TENANT_STATUS_ACTIVE = 1;</code>
   */
  TENANT_STATUS_ACTIVE(1),
  /**
   * <pre>
   * Suspended - tenant access is temporarily disabled (billing issue, policy violation).
   * </pre>
   *
   * <code>TENANT_STATUS_SUSPENDED = 2;</code>
   */
  TENANT_STATUS_SUSPENDED(2),
  /**
   * <pre>
   * Deleted - tenant is marked for deletion (soft delete, recoverable).
   * </pre>
   *
   * <code>TENANT_STATUS_DELETED = 3;</code>
   */
  TENANT_STATUS_DELETED(3),
  /**
   * <pre>
   * Trial - tenant is in trial period with limited features/duration.
   * </pre>
   *
   * <code>TENANT_STATUS_TRIAL = 4;</code>
   */
  TENANT_STATUS_TRIAL(4),
  /**
   * <pre>
   * Archived - tenant is permanently archived (hard delete pending).
   * </pre>
   *
   * <code>TENANT_STATUS_ARCHIVED = 5;</code>
   */
  TENANT_STATUS_ARCHIVED(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      TenantStatus.class.getName());
  }
  /**
   * <pre>
   * Default/unspecified status (invalid).
   * </pre>
   *
   * <code>TENANT_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int TENANT_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Active - tenant is operational and can make requests.
   * </pre>
   *
   * <code>TENANT_STATUS_ACTIVE = 1;</code>
   */
  public static final int TENANT_STATUS_ACTIVE_VALUE = 1;
  /**
   * <pre>
   * Suspended - tenant access is temporarily disabled (billing issue, policy violation).
   * </pre>
   *
   * <code>TENANT_STATUS_SUSPENDED = 2;</code>
   */
  public static final int TENANT_STATUS_SUSPENDED_VALUE = 2;
  /**
   * <pre>
   * Deleted - tenant is marked for deletion (soft delete, recoverable).
   * </pre>
   *
   * <code>TENANT_STATUS_DELETED = 3;</code>
   */
  public static final int TENANT_STATUS_DELETED_VALUE = 3;
  /**
   * <pre>
   * Trial - tenant is in trial period with limited features/duration.
   * </pre>
   *
   * <code>TENANT_STATUS_TRIAL = 4;</code>
   */
  public static final int TENANT_STATUS_TRIAL_VALUE = 4;
  /**
   * <pre>
   * Archived - tenant is permanently archived (hard delete pending).
   * </pre>
   *
   * <code>TENANT_STATUS_ARCHIVED = 5;</code>
   */
  public static final int TENANT_STATUS_ARCHIVED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TenantStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TenantStatus forNumber(int value) {
    switch (value) {
      case 0: return TENANT_STATUS_UNSPECIFIED;
      case 1: return TENANT_STATUS_ACTIVE;
      case 2: return TENANT_STATUS_SUSPENDED;
      case 3: return TENANT_STATUS_DELETED;
      case 4: return TENANT_STATUS_TRIAL;
      case 5: return TENANT_STATUS_ARCHIVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TenantStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TenantStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TenantStatus>() {
          public TenantStatus findValueByNumber(int number) {
            return TenantStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final TenantStatus[] VALUES = values();

  public static TenantStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TenantStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:core.v1.TenantStatus)
}

