// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

/**
 * <pre>
 * TenantInfo provides comprehensive configuration and metadata for a tenant.
 * This is returned by tenant management services and used for:
 * - Feature gating based on subscription tier
 * - Enforcing resource limits
 * - Compliance requirements
 * - Audit configuration
 * </pre>
 *
 * Protobuf type {@code core.v1.TenantInfo}
 */
public final class TenantInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.TenantInfo)
    TenantInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      TenantInfo.class.getName());
  }
  // Use TenantInfo.newBuilder() to construct.
  private TenantInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TenantInfo() {
    tenantId_ = "";
    name_ = "";
    status_ = 0;
    tier_ = 0;
    featureFlags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.geniustechspace.api.core.v1.TenantInfo.class, com.geniustechspace.api.core.v1.TenantInfo.Builder.class);
  }

  private int bitField0_;
  public static final int TENANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Unique tenant identifier (immutable).
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique tenant identifier (immutable).
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Human-readable display name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Human-readable display name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_ = 0;
  /**
   * <pre>
   * Current operational status of the tenant.
   * </pre>
   *
   * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Current operational status of the tenant.
   * </pre>
   *
   * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.geniustechspace.api.core.v1.TenantStatus getStatus() {
    com.geniustechspace.api.core.v1.TenantStatus result = com.geniustechspace.api.core.v1.TenantStatus.forNumber(status_);
    return result == null ? com.geniustechspace.api.core.v1.TenantStatus.UNRECOGNIZED : result;
  }

  public static final int TIER_FIELD_NUMBER = 4;
  private int tier_ = 0;
  /**
   * <pre>
   * Subscription tier - determines available features and limits.
   * </pre>
   *
   * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
   * @return The enum numeric value on the wire for tier.
   */
  @java.lang.Override public int getTierValue() {
    return tier_;
  }
  /**
   * <pre>
   * Subscription tier - determines available features and limits.
   * </pre>
   *
   * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
   * @return The tier.
   */
  @java.lang.Override public com.geniustechspace.api.core.v1.SubscriptionTier getTier() {
    com.geniustechspace.api.core.v1.SubscriptionTier result = com.geniustechspace.api.core.v1.SubscriptionTier.forNumber(tier_);
    return result == null ? com.geniustechspace.api.core.v1.SubscriptionTier.UNRECOGNIZED : result;
  }

  public static final int FEATURE_FLAGS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList featureFlags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @return A list containing the featureFlags.
   */
  public com.google.protobuf.ProtocolStringList
      getFeatureFlagsList() {
    return featureFlags_;
  }
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @return The count of featureFlags.
   */
  public int getFeatureFlagsCount() {
    return featureFlags_.size();
  }
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @param index The index of the element to return.
   * @return The featureFlags at the given index.
   */
  public java.lang.String getFeatureFlags(int index) {
    return featureFlags_.get(index);
  }
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the featureFlags at the given index.
   */
  public com.google.protobuf.ByteString
      getFeatureFlagsBytes(int index) {
    return featureFlags_.getByteString(index);
  }

  public static final int LIMITS_FIELD_NUMBER = 6;
  private com.geniustechspace.api.core.v1.ResourceLimits limits_;
  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   * @return Whether the limits field is set.
   */
  @java.lang.Override
  public boolean hasLimits() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   * @return The limits.
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.ResourceLimits getLimits() {
    return limits_ == null ? com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance() : limits_;
  }
  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder getLimitsOrBuilder() {
    return limits_ == null ? com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance() : limits_;
  }

  public static final int COMPLIANCE_FIELD_NUMBER = 7;
  private com.geniustechspace.api.core.v1.ComplianceSettings compliance_;
  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   * @return Whether the compliance field is set.
   */
  @java.lang.Override
  public boolean hasCompliance() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   * @return The compliance.
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.ComplianceSettings getCompliance() {
    return compliance_ == null ? com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance() : compliance_;
  }
  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder getComplianceOrBuilder() {
    return compliance_ == null ? com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance() : compliance_;
  }

  public static final int AUDIT_FIELD_NUMBER = 8;
  private com.geniustechspace.api.core.v1.AuditSettings audit_;
  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   * @return Whether the audit field is set.
   */
  @java.lang.Override
  public boolean hasAudit() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   * @return The audit.
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.AuditSettings getAudit() {
    return audit_ == null ? com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance() : audit_;
  }
  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   */
  @java.lang.Override
  public com.geniustechspace.api.core.v1.AuditSettingsOrBuilder getAuditOrBuilder() {
    return audit_ == null ? com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance() : audit_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 20;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 21;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  public static final int DELETED_AT_FIELD_NUMBER = 22;
  private com.google.protobuf.Timestamp deletedAt_;
  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   * @return Whether the deletedAt field is set.
   */
  @java.lang.Override
  public boolean hasDeletedAt() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   * @return The deletedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeletedAt() {
    return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
  }
  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
    return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (status_ != com.geniustechspace.api.core.v1.TenantStatus.TENANT_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (tier_ != com.geniustechspace.api.core.v1.SubscriptionTier.SUBSCRIPTION_TIER_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, tier_);
    }
    for (int i = 0; i < featureFlags_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, featureFlags_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getLimits());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getCompliance());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(8, getAudit());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(20, getCreatedAt());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(21, getUpdatedAt());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(22, getDeletedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (status_ != com.geniustechspace.api.core.v1.TenantStatus.TENANT_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (tier_ != com.geniustechspace.api.core.v1.SubscriptionTier.SUBSCRIPTION_TIER_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, tier_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < featureFlags_.size(); i++) {
        dataSize += computeStringSizeNoTag(featureFlags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFeatureFlagsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLimits());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getCompliance());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getAudit());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getCreatedAt());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getUpdatedAt());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getDeletedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.geniustechspace.api.core.v1.TenantInfo)) {
      return super.equals(obj);
    }
    com.geniustechspace.api.core.v1.TenantInfo other = (com.geniustechspace.api.core.v1.TenantInfo) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (status_ != other.status_) return false;
    if (tier_ != other.tier_) return false;
    if (!getFeatureFlagsList()
        .equals(other.getFeatureFlagsList())) return false;
    if (hasLimits() != other.hasLimits()) return false;
    if (hasLimits()) {
      if (!getLimits()
          .equals(other.getLimits())) return false;
    }
    if (hasCompliance() != other.hasCompliance()) return false;
    if (hasCompliance()) {
      if (!getCompliance()
          .equals(other.getCompliance())) return false;
    }
    if (hasAudit() != other.hasAudit()) return false;
    if (hasAudit()) {
      if (!getAudit()
          .equals(other.getAudit())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (hasDeletedAt() != other.hasDeletedAt()) return false;
    if (hasDeletedAt()) {
      if (!getDeletedAt()
          .equals(other.getDeletedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + TIER_FIELD_NUMBER;
    hash = (53 * hash) + tier_;
    if (getFeatureFlagsCount() > 0) {
      hash = (37 * hash) + FEATURE_FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureFlagsList().hashCode();
    }
    if (hasLimits()) {
      hash = (37 * hash) + LIMITS_FIELD_NUMBER;
      hash = (53 * hash) + getLimits().hashCode();
    }
    if (hasCompliance()) {
      hash = (37 * hash) + COMPLIANCE_FIELD_NUMBER;
      hash = (53 * hash) + getCompliance().hashCode();
    }
    if (hasAudit()) {
      hash = (37 * hash) + AUDIT_FIELD_NUMBER;
      hash = (53 * hash) + getAudit().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    if (hasDeletedAt()) {
      hash = (37 * hash) + DELETED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDeletedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.geniustechspace.api.core.v1.TenantInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.geniustechspace.api.core.v1.TenantInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.geniustechspace.api.core.v1.TenantInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.geniustechspace.api.core.v1.TenantInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TenantInfo provides comprehensive configuration and metadata for a tenant.
   * This is returned by tenant management services and used for:
   * - Feature gating based on subscription tier
   * - Enforcing resource limits
   * - Compliance requirements
   * - Audit configuration
   * </pre>
   *
   * Protobuf type {@code core.v1.TenantInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.TenantInfo)
      com.geniustechspace.api.core.v1.TenantInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.geniustechspace.api.core.v1.TenantInfo.class, com.geniustechspace.api.core.v1.TenantInfo.Builder.class);
    }

    // Construct using com.geniustechspace.api.core.v1.TenantInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLimitsFieldBuilder();
        getComplianceFieldBuilder();
        getAuditFieldBuilder();
        getCreatedAtFieldBuilder();
        getUpdatedAtFieldBuilder();
        getDeletedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = "";
      name_ = "";
      status_ = 0;
      tier_ = 0;
      featureFlags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      limits_ = null;
      if (limitsBuilder_ != null) {
        limitsBuilder_.dispose();
        limitsBuilder_ = null;
      }
      compliance_ = null;
      if (complianceBuilder_ != null) {
        complianceBuilder_.dispose();
        complianceBuilder_ = null;
      }
      audit_ = null;
      if (auditBuilder_ != null) {
        auditBuilder_.dispose();
        auditBuilder_ = null;
      }
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      deletedAt_ = null;
      if (deletedAtBuilder_ != null) {
        deletedAtBuilder_.dispose();
        deletedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.geniustechspace.api.core.v1.TenantProto.internal_static_core_v1_TenantInfo_descriptor;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantInfo getDefaultInstanceForType() {
      return com.geniustechspace.api.core.v1.TenantInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantInfo build() {
      com.geniustechspace.api.core.v1.TenantInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantInfo buildPartial() {
      com.geniustechspace.api.core.v1.TenantInfo result = new com.geniustechspace.api.core.v1.TenantInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.geniustechspace.api.core.v1.TenantInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tier_ = tier_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        featureFlags_.makeImmutable();
        result.featureFlags_ = featureFlags_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.limits_ = limitsBuilder_ == null
            ? limits_
            : limitsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.compliance_ = complianceBuilder_ == null
            ? compliance_
            : complianceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.audit_ = auditBuilder_ == null
            ? audit_
            : auditBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.deletedAt_ = deletedAtBuilder_ == null
            ? deletedAt_
            : deletedAtBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.geniustechspace.api.core.v1.TenantInfo) {
        return mergeFrom((com.geniustechspace.api.core.v1.TenantInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.geniustechspace.api.core.v1.TenantInfo other) {
      if (other == com.geniustechspace.api.core.v1.TenantInfo.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.tier_ != 0) {
        setTierValue(other.getTierValue());
      }
      if (!other.featureFlags_.isEmpty()) {
        if (featureFlags_.isEmpty()) {
          featureFlags_ = other.featureFlags_;
          bitField0_ |= 0x00000010;
        } else {
          ensureFeatureFlagsIsMutable();
          featureFlags_.addAll(other.featureFlags_);
        }
        onChanged();
      }
      if (other.hasLimits()) {
        mergeLimits(other.getLimits());
      }
      if (other.hasCompliance()) {
        mergeCompliance(other.getCompliance());
      }
      if (other.hasAudit()) {
        mergeAudit(other.getAudit());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      if (other.hasDeletedAt()) {
        mergeDeletedAt(other.getDeletedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              tier_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFeatureFlagsIsMutable();
              featureFlags_.add(s);
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getLimitsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getComplianceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getAuditFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 162: {
              input.readMessage(
                  getCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 162
            case 170: {
              input.readMessage(
                  getUpdatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 170
            case 178: {
              input.readMessage(
                  getDeletedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 178
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Unique tenant identifier (immutable).
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique tenant identifier (immutable).
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique tenant identifier (immutable).
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique tenant identifier (immutable).
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique tenant identifier (immutable).
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Human-readable display name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Human-readable display name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Human-readable display name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable display name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable display name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Current operational status of the tenant.
     * </pre>
     *
     * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Current operational status of the tenant.
     * </pre>
     *
     * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current operational status of the tenant.
     * </pre>
     *
     * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.geniustechspace.api.core.v1.TenantStatus getStatus() {
      com.geniustechspace.api.core.v1.TenantStatus result = com.geniustechspace.api.core.v1.TenantStatus.forNumber(status_);
      return result == null ? com.geniustechspace.api.core.v1.TenantStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Current operational status of the tenant.
     * </pre>
     *
     * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.geniustechspace.api.core.v1.TenantStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current operational status of the tenant.
     * </pre>
     *
     * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    private int tier_ = 0;
    /**
     * <pre>
     * Subscription tier - determines available features and limits.
     * </pre>
     *
     * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
     * @return The enum numeric value on the wire for tier.
     */
    @java.lang.Override public int getTierValue() {
      return tier_;
    }
    /**
     * <pre>
     * Subscription tier - determines available features and limits.
     * </pre>
     *
     * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
     * @param value The enum numeric value on the wire for tier to set.
     * @return This builder for chaining.
     */
    public Builder setTierValue(int value) {
      tier_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscription tier - determines available features and limits.
     * </pre>
     *
     * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
     * @return The tier.
     */
    @java.lang.Override
    public com.geniustechspace.api.core.v1.SubscriptionTier getTier() {
      com.geniustechspace.api.core.v1.SubscriptionTier result = com.geniustechspace.api.core.v1.SubscriptionTier.forNumber(tier_);
      return result == null ? com.geniustechspace.api.core.v1.SubscriptionTier.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Subscription tier - determines available features and limits.
     * </pre>
     *
     * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
     * @param value The tier to set.
     * @return This builder for chaining.
     */
    public Builder setTier(com.geniustechspace.api.core.v1.SubscriptionTier value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      tier_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscription tier - determines available features and limits.
     * </pre>
     *
     * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTier() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tier_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList featureFlags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFeatureFlagsIsMutable() {
      if (!featureFlags_.isModifiable()) {
        featureFlags_ = new com.google.protobuf.LazyStringArrayList(featureFlags_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @return A list containing the featureFlags.
     */
    public com.google.protobuf.ProtocolStringList
        getFeatureFlagsList() {
      featureFlags_.makeImmutable();
      return featureFlags_;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @return The count of featureFlags.
     */
    public int getFeatureFlagsCount() {
      return featureFlags_.size();
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param index The index of the element to return.
     * @return The featureFlags at the given index.
     */
    public java.lang.String getFeatureFlags(int index) {
      return featureFlags_.get(index);
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the featureFlags at the given index.
     */
    public com.google.protobuf.ByteString
        getFeatureFlagsBytes(int index) {
      return featureFlags_.getByteString(index);
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param index The index to set the value at.
     * @param value The featureFlags to set.
     * @return This builder for chaining.
     */
    public Builder setFeatureFlags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFeatureFlagsIsMutable();
      featureFlags_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param value The featureFlags to add.
     * @return This builder for chaining.
     */
    public Builder addFeatureFlags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFeatureFlagsIsMutable();
      featureFlags_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param values The featureFlags to add.
     * @return This builder for chaining.
     */
    public Builder addAllFeatureFlags(
        java.lang.Iterable<java.lang.String> values) {
      ensureFeatureFlagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, featureFlags_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFeatureFlags() {
      featureFlags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Feature flags enabled for this tenant.
     * Used for gradual feature rollout and A/B testing.
     * </pre>
     *
     * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
     * @param value The bytes of the featureFlags to add.
     * @return This builder for chaining.
     */
    public Builder addFeatureFlagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFeatureFlagsIsMutable();
      featureFlags_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.geniustechspace.api.core.v1.ResourceLimits limits_;
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.ResourceLimits, com.geniustechspace.api.core.v1.ResourceLimits.Builder, com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder> limitsBuilder_;
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     * @return Whether the limits field is set.
     */
    public boolean hasLimits() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     * @return The limits.
     */
    public com.geniustechspace.api.core.v1.ResourceLimits getLimits() {
      if (limitsBuilder_ == null) {
        return limits_ == null ? com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance() : limits_;
      } else {
        return limitsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public Builder setLimits(com.geniustechspace.api.core.v1.ResourceLimits value) {
      if (limitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        limits_ = value;
      } else {
        limitsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public Builder setLimits(
        com.geniustechspace.api.core.v1.ResourceLimits.Builder builderForValue) {
      if (limitsBuilder_ == null) {
        limits_ = builderForValue.build();
      } else {
        limitsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public Builder mergeLimits(com.geniustechspace.api.core.v1.ResourceLimits value) {
      if (limitsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          limits_ != null &&
          limits_ != com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance()) {
          getLimitsBuilder().mergeFrom(value);
        } else {
          limits_ = value;
        }
      } else {
        limitsBuilder_.mergeFrom(value);
      }
      if (limits_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public Builder clearLimits() {
      bitField0_ = (bitField0_ & ~0x00000020);
      limits_ = null;
      if (limitsBuilder_ != null) {
        limitsBuilder_.dispose();
        limitsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public com.geniustechspace.api.core.v1.ResourceLimits.Builder getLimitsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getLimitsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    public com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder getLimitsOrBuilder() {
      if (limitsBuilder_ != null) {
        return limitsBuilder_.getMessageOrBuilder();
      } else {
        return limits_ == null ?
            com.geniustechspace.api.core.v1.ResourceLimits.getDefaultInstance() : limits_;
      }
    }
    /**
     * <pre>
     * Resource usage limits for this tenant.
     * </pre>
     *
     * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.ResourceLimits, com.geniustechspace.api.core.v1.ResourceLimits.Builder, com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder> 
        getLimitsFieldBuilder() {
      if (limitsBuilder_ == null) {
        limitsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.geniustechspace.api.core.v1.ResourceLimits, com.geniustechspace.api.core.v1.ResourceLimits.Builder, com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder>(
                getLimits(),
                getParentForChildren(),
                isClean());
        limits_ = null;
      }
      return limitsBuilder_;
    }

    private com.geniustechspace.api.core.v1.ComplianceSettings compliance_;
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.ComplianceSettings, com.geniustechspace.api.core.v1.ComplianceSettings.Builder, com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder> complianceBuilder_;
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     * @return Whether the compliance field is set.
     */
    public boolean hasCompliance() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     * @return The compliance.
     */
    public com.geniustechspace.api.core.v1.ComplianceSettings getCompliance() {
      if (complianceBuilder_ == null) {
        return compliance_ == null ? com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance() : compliance_;
      } else {
        return complianceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public Builder setCompliance(com.geniustechspace.api.core.v1.ComplianceSettings value) {
      if (complianceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        compliance_ = value;
      } else {
        complianceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public Builder setCompliance(
        com.geniustechspace.api.core.v1.ComplianceSettings.Builder builderForValue) {
      if (complianceBuilder_ == null) {
        compliance_ = builderForValue.build();
      } else {
        complianceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public Builder mergeCompliance(com.geniustechspace.api.core.v1.ComplianceSettings value) {
      if (complianceBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          compliance_ != null &&
          compliance_ != com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance()) {
          getComplianceBuilder().mergeFrom(value);
        } else {
          compliance_ = value;
        }
      } else {
        complianceBuilder_.mergeFrom(value);
      }
      if (compliance_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public Builder clearCompliance() {
      bitField0_ = (bitField0_ & ~0x00000040);
      compliance_ = null;
      if (complianceBuilder_ != null) {
        complianceBuilder_.dispose();
        complianceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public com.geniustechspace.api.core.v1.ComplianceSettings.Builder getComplianceBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getComplianceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    public com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder getComplianceOrBuilder() {
      if (complianceBuilder_ != null) {
        return complianceBuilder_.getMessageOrBuilder();
      } else {
        return compliance_ == null ?
            com.geniustechspace.api.core.v1.ComplianceSettings.getDefaultInstance() : compliance_;
      }
    }
    /**
     * <pre>
     * Compliance requirements and settings.
     * </pre>
     *
     * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.ComplianceSettings, com.geniustechspace.api.core.v1.ComplianceSettings.Builder, com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder> 
        getComplianceFieldBuilder() {
      if (complianceBuilder_ == null) {
        complianceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.geniustechspace.api.core.v1.ComplianceSettings, com.geniustechspace.api.core.v1.ComplianceSettings.Builder, com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder>(
                getCompliance(),
                getParentForChildren(),
                isClean());
        compliance_ = null;
      }
      return complianceBuilder_;
    }

    private com.geniustechspace.api.core.v1.AuditSettings audit_;
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.AuditSettings, com.geniustechspace.api.core.v1.AuditSettings.Builder, com.geniustechspace.api.core.v1.AuditSettingsOrBuilder> auditBuilder_;
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     * @return Whether the audit field is set.
     */
    public boolean hasAudit() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     * @return The audit.
     */
    public com.geniustechspace.api.core.v1.AuditSettings getAudit() {
      if (auditBuilder_ == null) {
        return audit_ == null ? com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance() : audit_;
      } else {
        return auditBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public Builder setAudit(com.geniustechspace.api.core.v1.AuditSettings value) {
      if (auditBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audit_ = value;
      } else {
        auditBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public Builder setAudit(
        com.geniustechspace.api.core.v1.AuditSettings.Builder builderForValue) {
      if (auditBuilder_ == null) {
        audit_ = builderForValue.build();
      } else {
        auditBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public Builder mergeAudit(com.geniustechspace.api.core.v1.AuditSettings value) {
      if (auditBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          audit_ != null &&
          audit_ != com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance()) {
          getAuditBuilder().mergeFrom(value);
        } else {
          audit_ = value;
        }
      } else {
        auditBuilder_.mergeFrom(value);
      }
      if (audit_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public Builder clearAudit() {
      bitField0_ = (bitField0_ & ~0x00000080);
      audit_ = null;
      if (auditBuilder_ != null) {
        auditBuilder_.dispose();
        auditBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public com.geniustechspace.api.core.v1.AuditSettings.Builder getAuditBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getAuditFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    public com.geniustechspace.api.core.v1.AuditSettingsOrBuilder getAuditOrBuilder() {
      if (auditBuilder_ != null) {
        return auditBuilder_.getMessageOrBuilder();
      } else {
        return audit_ == null ?
            com.geniustechspace.api.core.v1.AuditSettings.getDefaultInstance() : audit_;
      }
    }
    /**
     * <pre>
     * Audit logging configuration.
     * </pre>
     *
     * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.geniustechspace.api.core.v1.AuditSettings, com.geniustechspace.api.core.v1.AuditSettings.Builder, com.geniustechspace.api.core.v1.AuditSettingsOrBuilder> 
        getAuditFieldBuilder() {
      if (auditBuilder_ == null) {
        auditBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.geniustechspace.api.core.v1.AuditSettings, com.geniustechspace.api.core.v1.AuditSettings.Builder, com.geniustechspace.api.core.v1.AuditSettingsOrBuilder>(
                getAudit(),
                getParentForChildren(),
                isClean());
        audit_ = null;
      }
      return auditBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000100);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      if (updatedAt_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000200);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was last updated.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private com.google.protobuf.Timestamp deletedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedAtBuilder_;
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     * @return Whether the deletedAt field is set.
     */
    public boolean hasDeletedAt() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     * @return The deletedAt.
     */
    public com.google.protobuf.Timestamp getDeletedAt() {
      if (deletedAtBuilder_ == null) {
        return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
      } else {
        return deletedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public Builder setDeletedAt(com.google.protobuf.Timestamp value) {
      if (deletedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deletedAt_ = value;
      } else {
        deletedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public Builder setDeletedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deletedAtBuilder_ == null) {
        deletedAt_ = builderForValue.build();
      } else {
        deletedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public Builder mergeDeletedAt(com.google.protobuf.Timestamp value) {
      if (deletedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          deletedAt_ != null &&
          deletedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDeletedAtBuilder().mergeFrom(value);
        } else {
          deletedAt_ = value;
        }
      } else {
        deletedAtBuilder_.mergeFrom(value);
      }
      if (deletedAt_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public Builder clearDeletedAt() {
      bitField0_ = (bitField0_ & ~0x00000400);
      deletedAt_ = null;
      if (deletedAtBuilder_ != null) {
        deletedAtBuilder_.dispose();
        deletedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeletedAtBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getDeletedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
      if (deletedAtBuilder_ != null) {
        return deletedAtBuilder_.getMessageOrBuilder();
      } else {
        return deletedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when tenant was deleted (soft delete).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDeletedAtFieldBuilder() {
      if (deletedAtBuilder_ == null) {
        deletedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeletedAt(),
                getParentForChildren(),
                isClean());
        deletedAt_ = null;
      }
      return deletedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.TenantInfo)
  }

  // @@protoc_insertion_point(class_scope:core.v1.TenantInfo)
  private static final com.geniustechspace.api.core.v1.TenantInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.geniustechspace.api.core.v1.TenantInfo();
  }

  public static com.geniustechspace.api.core.v1.TenantInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TenantInfo>
      PARSER = new com.google.protobuf.AbstractParser<TenantInfo>() {
    @java.lang.Override
    public TenantInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TenantInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TenantInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.geniustechspace.api.core.v1.TenantInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

