// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public final class TenantProto {
  private TenantProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      TenantProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_TenantContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_TenantContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_TenantContext_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_TenantContext_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_TenantInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_TenantInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_ResourceLimits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_ResourceLimits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_ResourceLimits_CustomLimitsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_ResourceLimits_CustomLimitsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_ComplianceSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_ComplianceSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_DataResidency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_DataResidency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_AuditSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_AuditSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024core/v1/tenant.proto\022\007core.v1\032\037google/" +
      "protobuf/timestamp.proto\032\027validate/valid" +
      "ate.proto\"\336\002\n\rTenantContext\0228\n\ttenant_id" +
      "\030\001 \001(\tB\033\372B\030r\026\020\001\030@2\020^[a-zA-Z0-9_-]+$R\010ten" +
      "antId\0220\n\017organization_id\030\002 \001(\tB\007\372B\004r\002\030@R" +
      "\016organizationId\022*\n\014workspace_id\030\003 \001(\tB\007\372" +
      "B\004r\002\030@R\013workspaceId\0226\n\013environment\030\004 \001(\016" +
      "2\024.core.v1.EnvironmentR\013environment\022@\n\010m" +
      "etadata\030\005 \003(\0132$.core.v1.TenantContext.Me" +
      "tadataEntryR\010metadata\032;\n\rMetadataEntry\022\020" +
      "\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\002" +
      "8\001\"\242\004\n\nTenantInfo\022$\n\ttenant_id\030\001 \001(\tB\007\372B" +
      "\004r\002\020\001R\010tenantId\022\036\n\004name\030\002 \001(\tB\n\372B\007r\005\020\001\030\377" +
      "\001R\004name\022-\n\006status\030\003 \001(\0162\025.core.v1.Tenant" +
      "StatusR\006status\022-\n\004tier\030\004 \001(\0162\031.core.v1.S" +
      "ubscriptionTierR\004tier\022#\n\rfeature_flags\030\005" +
      " \003(\tR\014featureFlags\022/\n\006limits\030\006 \001(\0132\027.cor" +
      "e.v1.ResourceLimitsR\006limits\022;\n\ncomplianc" +
      "e\030\007 \001(\0132\033.core.v1.ComplianceSettingsR\nco" +
      "mpliance\022,\n\005audit\030\010 \001(\0132\026.core.v1.AuditS" +
      "ettingsR\005audit\0229\n\ncreated_at\030\024 \001(\0132\032.goo" +
      "gle.protobuf.TimestampR\tcreatedAt\0229\n\nupd" +
      "ated_at\030\025 \001(\0132\032.google.protobuf.Timestam" +
      "pR\tupdatedAt\0229\n\ndeleted_at\030\026 \001(\0132\032.googl" +
      "e.protobuf.TimestampR\tdeletedAt\"\362\003\n\016Reso" +
      "urceLimits\022$\n\tmax_users\030\001 \001(\005B\007\372B\004\032\002(\000R\010" +
      "maxUsers\022?\n\030max_api_calls_per_minute\030\002 \001" +
      "(\005B\007\372B\004\032\002(\000R\024maxApiCallsPerMinute\0223\n\021max" +
      "_storage_bytes\030\003 \001(\003B\007\372B\004\"\002(\000R\017maxStorag" +
      "eBytes\022?\n\027max_concurrent_sessions\030\004 \001(\005B" +
      "\007\372B\004\032\002(\000R\025maxConcurrentSessions\0224\n\021max_o" +
      "rganizations\030\005 \001(\005B\007\372B\004\032\002(\000R\020maxOrganiza" +
      "tions\022<\n\026max_workspaces_per_org\030\006 \001(\005B\007\372" +
      "B\004\032\002(\000R\023maxWorkspacesPerOrg\022N\n\rcustom_li" +
      "mits\030\n \003(\0132).core.v1.ResourceLimits.Cust" +
      "omLimitsEntryR\014customLimits\032?\n\021CustomLim" +
      "itsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(" +
      "\003R\005value:\0028\001\"\246\003\n\022ComplianceSettings\022!\n\014g" +
      "dpr_enabled\030\001 \001(\010R\013gdprEnabled\022#\n\rhipaa_" +
      "enabled\030\002 \001(\010R\014hipaaEnabled\022!\n\014soc2_enab" +
      "led\030\003 \001(\010R\013soc2Enabled\022&\n\017pci_dss_enable" +
      "d\030\004 \001(\010R\rpciDssEnabled\022=\n\016data_residency" +
      "\030\005 \001(\0132\026.core.v1.DataResidencyR\rdataResi" +
      "dency\022:\n\023data_retention_days\030\006 \001(\005B\n\372B\007\032" +
      "\005\030\302\034(\000R\021dataRetentionDays\022=\n\033encryption_" +
      "at_rest_required\030\007 \001(\010R\030encryptionAtRest" +
      "Required\022C\n\036encryption_in_transit_requir" +
      "ed\030\010 \001(\010R\033encryptionInTransitRequired\"\227\001" +
      "\n\rDataResidency\022\'\n\017allowed_regions\030\001 \003(\t" +
      "R\016allowedRegions\022-\n\022prohibited_regions\030\002" +
      " \003(\tR\021prohibitedRegions\022.\n\016primary_regio" +
      "n\030\003 \001(\tB\007\372B\004r\002\030\nR\rprimaryRegion\"\364\001\n\rAudi" +
      "tSettings\022\030\n\007enabled\030\001 \001(\010R\007enabled\0221\n\016r" +
      "etention_days\030\002 \001(\005B\n\372B\007\032\005\030\302\034(\000R\rretenti" +
      "onDays\0228\n\013event_types\030\003 \003(\0162\027.core.v1.Au" +
      "ditEventTypeR\neventTypes\022;\n\024external_des" +
      "tination\030\004 \001(\tB\010\372B\005r\003\030\200\004R\023externalDestin" +
      "ation\022\037\n\013include_pii\030\005 \001(\010R\nincludePii*\222" +
      "\001\n\013Environment\022\033\n\027ENVIRONMENT_UNSPECIFIE" +
      "D\020\000\022\032\n\026ENVIRONMENT_PRODUCTION\020\001\022\027\n\023ENVIR" +
      "ONMENT_STAGING\020\002\022\033\n\027ENVIRONMENT_DEVELOPM" +
      "ENT\020\003\022\024\n\020ENVIRONMENT_TEST\020\004*\264\001\n\014TenantSt" +
      "atus\022\035\n\031TENANT_STATUS_UNSPECIFIED\020\000\022\030\n\024T" +
      "ENANT_STATUS_ACTIVE\020\001\022\033\n\027TENANT_STATUS_S" +
      "USPENDED\020\002\022\031\n\025TENANT_STATUS_DELETED\020\003\022\027\n" +
      "\023TENANT_STATUS_TRIAL\020\004\022\032\n\026TENANT_STATUS_" +
      "ARCHIVED\020\005*\322\001\n\020SubscriptionTier\022!\n\035SUBSC" +
      "RIPTION_TIER_UNSPECIFIED\020\000\022\032\n\026SUBSCRIPTI" +
      "ON_TIER_FREE\020\001\022\033\n\027SUBSCRIPTION_TIER_BASI" +
      "C\020\002\022\"\n\036SUBSCRIPTION_TIER_PROFESSIONAL\020\003\022" +
      " \n\034SUBSCRIPTION_TIER_ENTERPRISE\020\004\022\034\n\030SUB" +
      "SCRIPTION_TIER_CUSTOM\020\005*\341\002\n\016AuditEventTy" +
      "pe\022 \n\034AUDIT_EVENT_TYPE_UNSPECIFIED\020\000\022#\n\037" +
      "AUDIT_EVENT_TYPE_AUTHENTICATION\020\001\022\"\n\036AUD" +
      "IT_EVENT_TYPE_AUTHORIZATION\020\002\022 \n\034AUDIT_E" +
      "VENT_TYPE_DATA_ACCESS\020\003\022&\n\"AUDIT_EVENT_T" +
      "YPE_DATA_MODIFICATION\020\004\022)\n%AUDIT_EVENT_T" +
      "YPE_CONFIGURATION_CHANGE\020\005\022#\n\037AUDIT_EVEN" +
      "T_TYPE_SECURITY_EVENT\020\006\022%\n!AUDIT_EVENT_T" +
      "YPE_COMPLIANCE_EVENT\020\007\022#\n\037AUDIT_EVENT_TY" +
      "PE_ADMINISTRATIVE\020\010B\253\001\n\037com.geniustechsp" +
      "ace.api.core.v1B\013TenantProtoP\001Z>github.c" +
      "om/geniustechspace/api-contracts/gen/go/" +
      "core/v1;corev1\242\002\003CXX\252\002\007Core.V1\312\002\007Core\\V1" +
      "\342\002\023Core\\V1\\GPBMetadata\352\002\010Core::V1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.geniustechspace.api.validate.ValidateProto.getDescriptor(),
        });
    internal_static_core_v1_TenantContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_v1_TenantContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_TenantContext_descriptor,
        new java.lang.String[] { "TenantId", "OrganizationId", "WorkspaceId", "Environment", "Metadata", });
    internal_static_core_v1_TenantContext_MetadataEntry_descriptor =
      internal_static_core_v1_TenantContext_descriptor.getNestedTypes().get(0);
    internal_static_core_v1_TenantContext_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_TenantContext_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_core_v1_TenantInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_v1_TenantInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_TenantInfo_descriptor,
        new java.lang.String[] { "TenantId", "Name", "Status", "Tier", "FeatureFlags", "Limits", "Compliance", "Audit", "CreatedAt", "UpdatedAt", "DeletedAt", });
    internal_static_core_v1_ResourceLimits_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_core_v1_ResourceLimits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_ResourceLimits_descriptor,
        new java.lang.String[] { "MaxUsers", "MaxApiCallsPerMinute", "MaxStorageBytes", "MaxConcurrentSessions", "MaxOrganizations", "MaxWorkspacesPerOrg", "CustomLimits", });
    internal_static_core_v1_ResourceLimits_CustomLimitsEntry_descriptor =
      internal_static_core_v1_ResourceLimits_descriptor.getNestedTypes().get(0);
    internal_static_core_v1_ResourceLimits_CustomLimitsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_ResourceLimits_CustomLimitsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_core_v1_ComplianceSettings_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_core_v1_ComplianceSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_ComplianceSettings_descriptor,
        new java.lang.String[] { "GdprEnabled", "HipaaEnabled", "Soc2Enabled", "PciDssEnabled", "DataResidency", "DataRetentionDays", "EncryptionAtRestRequired", "EncryptionInTransitRequired", });
    internal_static_core_v1_DataResidency_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_core_v1_DataResidency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_DataResidency_descriptor,
        new java.lang.String[] { "AllowedRegions", "ProhibitedRegions", "PrimaryRegion", });
    internal_static_core_v1_AuditSettings_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_core_v1_AuditSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_AuditSettings_descriptor,
        new java.lang.String[] { "Enabled", "RetentionDays", "EventTypes", "ExternalDestination", "IncludePii", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.geniustechspace.api.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.geniustechspace.api.validate.ValidateProto.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
