// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/tenant.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.core.v1;

public interface TenantInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.TenantInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique tenant identifier (immutable).
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * Unique tenant identifier (immutable).
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenantId", (.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * Human-readable display name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Human-readable display name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Current operational status of the tenant.
   * </pre>
   *
   * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Current operational status of the tenant.
   * </pre>
   *
   * <code>.core.v1.TenantStatus status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  com.geniustechspace.api.core.v1.TenantStatus getStatus();

  /**
   * <pre>
   * Subscription tier - determines available features and limits.
   * </pre>
   *
   * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
   * @return The enum numeric value on the wire for tier.
   */
  int getTierValue();
  /**
   * <pre>
   * Subscription tier - determines available features and limits.
   * </pre>
   *
   * <code>.core.v1.SubscriptionTier tier = 4 [json_name = "tier"];</code>
   * @return The tier.
   */
  com.geniustechspace.api.core.v1.SubscriptionTier getTier();

  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @return A list containing the featureFlags.
   */
  java.util.List<java.lang.String>
      getFeatureFlagsList();
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @return The count of featureFlags.
   */
  int getFeatureFlagsCount();
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @param index The index of the element to return.
   * @return The featureFlags at the given index.
   */
  java.lang.String getFeatureFlags(int index);
  /**
   * <pre>
   * Feature flags enabled for this tenant.
   * Used for gradual feature rollout and A/B testing.
   * </pre>
   *
   * <code>repeated string feature_flags = 5 [json_name = "featureFlags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the featureFlags at the given index.
   */
  com.google.protobuf.ByteString
      getFeatureFlagsBytes(int index);

  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   * @return Whether the limits field is set.
   */
  boolean hasLimits();
  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   * @return The limits.
   */
  com.geniustechspace.api.core.v1.ResourceLimits getLimits();
  /**
   * <pre>
   * Resource usage limits for this tenant.
   * </pre>
   *
   * <code>.core.v1.ResourceLimits limits = 6 [json_name = "limits"];</code>
   */
  com.geniustechspace.api.core.v1.ResourceLimitsOrBuilder getLimitsOrBuilder();

  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   * @return Whether the compliance field is set.
   */
  boolean hasCompliance();
  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   * @return The compliance.
   */
  com.geniustechspace.api.core.v1.ComplianceSettings getCompliance();
  /**
   * <pre>
   * Compliance requirements and settings.
   * </pre>
   *
   * <code>.core.v1.ComplianceSettings compliance = 7 [json_name = "compliance"];</code>
   */
  com.geniustechspace.api.core.v1.ComplianceSettingsOrBuilder getComplianceOrBuilder();

  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   * @return Whether the audit field is set.
   */
  boolean hasAudit();
  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   * @return The audit.
   */
  com.geniustechspace.api.core.v1.AuditSettings getAudit();
  /**
   * <pre>
   * Audit logging configuration.
   * </pre>
   *
   * <code>.core.v1.AuditSettings audit = 8 [json_name = "audit"];</code>
   */
  com.geniustechspace.api.core.v1.AuditSettingsOrBuilder getAuditOrBuilder();

  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Timestamp when tenant was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 20 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <pre>
   * Timestamp when tenant was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated_at = 21 [json_name = "updatedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   * @return Whether the deletedAt field is set.
   */
  boolean hasDeletedAt();
  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   * @return The deletedAt.
   */
  com.google.protobuf.Timestamp getDeletedAt();
  /**
   * <pre>
   * Timestamp when tenant was deleted (soft delete).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp deleted_at = 22 [json_name = "deletedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder();
}
