// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: validate/validate.proto
// Protobuf Java Version: 4.28.3

package com.geniustechspace.api.validate;

public interface BoolRulesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:validate.BoolRules)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Const specifies that this field must be exactly the specified value
   * </pre>
   *
   * <code>optional bool const = 1 [json_name = "const"];</code>
   * @return Whether the const field is set.
   */
  boolean hasConst();
  /**
   * <pre>
   * Const specifies that this field must be exactly the specified value
   * </pre>
   *
   * <code>optional bool const = 1 [json_name = "const"];</code>
   * @return The const.
   */
  boolean getConst();
}
